/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2024-12-23 04:44:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.User;
import model.GioHang;
import java.util.List;
import Reponsitory.Laydulieuchonguoidung;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("model.GioHang");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("Reponsitory.Laydulieuchonguoidung");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Liên hệ</title>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--===============================================================================================-->	\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" href=\"images/icons/favicon.png\"/>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/iconic/css/material-design-iconic-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/linearicons-v1.0.0/icon-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animate/animate.css\">\r\n");
      out.write("<!--===============================================================================================-->	\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/select2/select2.min.css\">\r\n");
      out.write("<!--===============================================================================================-->	\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/slick/slick.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/MagnificPopup/magnific-popup.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/perfect-scrollbar/perfect-scrollbar.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/util.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<style>\r\n");
      out.write(".d-none {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".d-block {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write(".icon-header-dropdown {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("    display: none; /* Ẩn menu mặc định */\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 100%;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul li {\r\n");
      out.write("    padding: 8px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul li a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-header-dropdown:hover .dropdown-menu {\r\n");
      out.write("    display: block; /* Hiển thị menu khi hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"animsition\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	<header class=\"header-v4\">\r\n");
      out.write("		<!-- Header desktop -->\r\n");
      out.write("		<div class=\"container-menu-desktop\">\r\n");
      out.write("			<!-- Topbar -->\r\n");
      out.write("			<div class=\"top-bar\">\r\n");
      out.write("				<div class=\"content-topbar flex-sb-m h-full container\">\r\n");
      out.write("					<div class=\"left-top-bar\">\r\n");
      out.write("						Web bán hàng thời trang phong cách \r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"wrap-menu-desktop how-shadow1\">\r\n");
      out.write("				<nav class=\"limiter-menu-desktop container\">\r\n");
      out.write("					\r\n");
      out.write("					<!-- Logo desktop -->		\r\n");
      out.write("					<a href=\"Laydulieusanpham\" class=\"logo\">\r\n");
      out.write("						<img src=\"assetsquantri/img/logo.png\" alt=\"IMG-LOGO\">\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<!-- Menu desktop -->\r\n");
      out.write("					<div class=\"menu-desktop\">\r\n");
      out.write("						<ul class=\"main-menu\">\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"Laydulieusanpham\">Trang chủ</a>\r\n");
      out.write("								 \r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li >\r\n");
      out.write("								<a href=\"Cuahang\">Cửa hàng</a>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li  class=\"label1\" data-label1=\"hot\">\r\n");
      out.write("								<a href=\"Giohang\">Giỏ hàng</a>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"blog.jsp\">Blog</a>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"about.jsp\">Giới thiệu</a>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"active-menu\">\r\n");
      out.write("								<a href=\"contact.jsp\">Liên hệ</a>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>	\r\n");
      out.write("\r\n");
      out.write("					<!-- Icon header -->\r\n");
      out.write("					<div class=\"wrap-icon-header flex-w flex-r-m\">\r\n");
      out.write("						<div class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search\">\r\n");
      out.write("							<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"wrap-icon-header flex-w flex-r-m\">\r\n");
      out.write("						<div class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search\">\r\n");
      out.write("							<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div\r\n");
      out.write("							");
Laydulieuchonguoidung lgn = new Laydulieuchonguoidung();
List<GioHang> gh = lgn.LayHetThongTinGioHang();
HttpSession tk = request.getSession(false);
List<User> user = (List<User>) tk.getAttribute("Ghinhotaikhoan");
int soluong = 0;
float tongTien = 0;
if (user != null) {
	for (GioHang gioHang : gh) {
		for (User u : user)
			if (u.getMaTaiKhoan() == gioHang.getMaNguoiDung()) {
				soluong += gioHang.getSoLuong();
				tongTien += gioHang.getGia();
			}
	}

}
      out.write("\r\n");
      out.write("							class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart\"\r\n");
      out.write("							data-notify=\"");
      out.print(soluong);
      out.write("\">\r\n");
      out.write("							<i class=\"zmdi zmdi-shopping-cart\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"icon-header-dropdown\">\r\n");
      out.write("							<a href=\"#\"\r\n");
      out.write("								class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11\">\r\n");
      out.write("								<i class=\"fa fa-user\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							<!-- Thẻ con chứa thông tin cá nhân và đơn hàng -->\r\n");
      out.write("							<div class=\"dropdown-menu\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"Thongtincanhan.jsp\">Thông tin cá nhân</a></li>\r\n");
      out.write("									<li><a href=\"Thongtindonhangdamua.jsp\">Đơn hàng</a></li>\r\n");
      out.write("									<li><a href=\"Dangxuat\">Đăng xuất</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>	\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Header Mobile -->\r\n");
      out.write("		<div class=\"wrap-header-mobile\">\r\n");
      out.write("			<!-- Logo moblie -->		\r\n");
      out.write("			<div class=\"logo-mobile\">\r\n");
      out.write("				<a href=\"Laydulieusanpham\"><img src=\"assetsquantri/img/logo.png\" alt=\"IMG-LOGO\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Icon header -->\r\n");
      out.write("			<div class=\"wrap-icon-header flex-w flex-r-m m-r-15\">\r\n");
      out.write("				<div class=\"icon-header-item cl2 hov-cl1 trans-04 p-r-11 js-show-modal-search\">\r\n");
      out.write("					<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"wrap-icon-header flex-w flex-r-m\">\r\n");
      out.write("						<div class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search\">\r\n");
      out.write("							<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div\r\n");
      out.write("							");

if (user != null) {
	for (GioHang gioHang : gh) {
		for (User u : user)
			if (u.getMaTaiKhoan() == gioHang.getMaNguoiDung()) {
				soluong += gioHang.getSoLuong();
				tongTien += gioHang.getGia();
			}
	}

}
      out.write("\r\n");
      out.write("							class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart\"\r\n");
      out.write("							data-notify=\"");
      out.print(soluong);
      out.write("\">\r\n");
      out.write("							<i class=\"zmdi zmdi-shopping-cart\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"icon-header-dropdown\">\r\n");
      out.write("							<a href=\"#\"\r\n");
      out.write("								class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11\">\r\n");
      out.write("								<i class=\"fa fa-user\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							<!-- Thẻ con chứa thông tin cá nhân và đơn hàng -->\r\n");
      out.write("							<div class=\"dropdown-menu\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"Thongtincanhan.jsp\">Thông tin cá nhân</a></li>\r\n");
      out.write("									<li><a href=\"Thongtindonhangdamua.jsp\">Đơn hàng</a></li>\r\n");
      out.write("									<li><a href=\"Dangxuat\">Đăng xuất</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Button show menu -->\r\n");
      out.write("			<div class=\"btn-show-menu-mobile hamburger hamburger--squeeze\">\r\n");
      out.write("				<span class=\"hamburger-box\">\r\n");
      out.write("					<span class=\"hamburger-inner\"></span>\r\n");
      out.write("				</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Menu Mobile -->\r\n");
      out.write("		<div class=\"menu-mobile\">\r\n");
      out.write("			<ul class=\"topbar-mobile\">\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"left-top-bar\">\r\n");
      out.write("						Trang web bán thời trang của tuấn\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"main-menu-m\">\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"Laydulieusanpham\">Trang chủ</a>\r\n");
      out.write("					\r\n");
      out.write("					<span class=\"arrow-main-menu-m\">\r\n");
      out.write("						<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("					</span>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"Cuahang\">Cửa hàng</a>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"Giohang\" class=\"label1 rs1\" data-label1=\"hot\">Giỏ hàng</a>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"blog.jsp\">Blog</a>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"about.jsp\">Giới thiệu</a>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"contact.jsp\">Liên hệ</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal Search -->\r\n");
      out.write("		<div class=\"modal-search-header flex-c-m trans-04 js-hide-modal-search\">\r\n");
      out.write("			<div class=\"container-search-header\">\r\n");
      out.write("				<button class=\"flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search\">\r\n");
      out.write("					<img src=\"images/icons/icon-close2.png\" alt=\"CLOSE\">\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<form class=\"wrap-search-header flex-w p-l-15\">\r\n");
      out.write("					<button class=\"flex-c-m trans-04\">\r\n");
      out.write("						<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("					<input class=\"plh3\" type=\"text\" name=\"search\" placeholder=\"Search...\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<!-- Cart -->\r\n");
      out.write("	<div class=\"wrap-header-cart js-panel-cart\">\r\n");
      out.write("		<div class=\"s-full js-hide-cart\"></div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"header-cart flex-col-l p-l-65 p-r-25\">\r\n");
      out.write("			<div class=\"header-cart-title flex-w flex-sb-m p-b-8\">\r\n");
      out.write("				<span class=\"mtext-103 cl2\">\r\n");
      out.write("					Giỏ hàng của bạn\r\n");
      out.write("				</span>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart\">\r\n");
      out.write("					<i class=\"zmdi zmdi-close\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"header-cart-content flex-w js-pscroll\">\r\n");
      out.write("				<ul class=\"header-cart-wrapitem w-full\">\r\n");
      out.write("					<li class=\"header-cart-item flex-w flex-t m-b-12\">\r\n");
      out.write("						<div class=\"header-cart-item-img\">\r\n");
      out.write("							<img src=\"images/item-cart-01.jpg\" alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"header-cart-item-txt p-t-8\">\r\n");
      out.write("							<a href=\"#\" class=\"header-cart-item-name m-b-18 hov-cl1 trans-04\">\r\n");
      out.write("								White Shirt Pleat\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							<span class=\"header-cart-item-info\">\r\n");
      out.write("								1 x $19.00\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"header-cart-item flex-w flex-t m-b-12\">\r\n");
      out.write("						<div class=\"header-cart-item-img\">\r\n");
      out.write("							<img src=\"images/item-cart-02.jpg\" alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"header-cart-item-txt p-t-8\">\r\n");
      out.write("							<a href=\"#\" class=\"header-cart-item-name m-b-18 hov-cl1 trans-04\">\r\n");
      out.write("								Converse All Star\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							<span class=\"header-cart-item-info\">\r\n");
      out.write("								1 x $39.00\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"header-cart-item flex-w flex-t m-b-12\">\r\n");
      out.write("						<div class=\"header-cart-item-img\">\r\n");
      out.write("							<img src=\"images/item-cart-03.jpg\" alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"header-cart-item-txt p-t-8\">\r\n");
      out.write("							<a href=\"#\" class=\"header-cart-item-name m-b-18 hov-cl1 trans-04\">\r\n");
      out.write("								Nixon Porter Leather\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							<span class=\"header-cart-item-info\">\r\n");
      out.write("								1 x $17.00\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"w-full\">\r\n");
      out.write("					<div class=\"header-cart-total w-full p-tb-40\">\r\n");
      out.write("						Tổng: $75.00\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"header-cart-buttons flex-w w-full\">\r\n");
      out.write("						<a href=\"shoping-cart.html\" class=\"flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10\">\r\n");
      out.write("							Xem giỏ hàng\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("						<a href=\"shoping-cart.html\" class=\"flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10\">\r\n");
      out.write("							Kiểm tra\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Title page -->\r\n");
      out.write("	<section class=\"bg-img1 txt-center p-lr-15 p-tb-92\" style=\"background-image: url('images/bg-01.jpg');\">\r\n");
      out.write("		<h2 class=\"ltext-105 cl0 txt-center\">\r\n");
      out.write("			Liên hệ\r\n");
      out.write("		</h2>\r\n");
      out.write("	</section>	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Content page -->\r\n");
      out.write("	<section class=\"bg0 p-t-104 p-b-116\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"flex-w flex-tr\">\r\n");
      out.write("				<div class=\"size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md\">\r\n");
      out.write("					<form action=\"Emailweb\" method=\"post\">\r\n");
      out.write("						<h4 class=\"mtext-105 cl2 txt-center p-b-30\">\r\n");
      out.write("							Để lại tin nhắn cho chúng tôi\r\n");
      out.write("						</h4>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"bor8 m-b-20 how-pos4-parent\">\r\n");
      out.write("							<input class=\"stext-111 cl2 plh3 size-116 p-l-62 p-r-30\" type=\"text\" name=\"email\" placeholder=\"Địa chỉ email\" value=\"ntuan4753@gmail.com\">\r\n");
      out.write("							<img class=\"how-pos4 pointer-none\" src=\"images/icons/icon-email.png\" alt=\"ICON\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"bor8 m-b-30\">\r\n");
      out.write("							<textarea class=\"stext-111 cl2 plh3 size-120 p-lr-28 p-tb-25\" name=\"msg\" placeholder=\"Chúng tôi có thể giúp gì cho bạn?\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<button class=\"flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer\">\r\n");
      out.write("							Gửi\r\n");
      out.write("						</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				
				String guiMailThanhCong = (String) request.getAttribute("guimailthanhcong");
				String guiMailThatBai = (String) request.getAttribute("guimailthatbai");
				if(guiMailThanhCong != null){
				
      out.write("\r\n");
      out.write("				<script>\r\n");
      out.write("				alert(\"Gửi mail thành công roài hehe\");\r\n");
      out.write("				</script>\r\n");
      out.write("				\r\n");
      out.write("				");
} if(guiMailThatBai != null){
      out.write("\r\n");
      out.write("				<script>\r\n");
      out.write("				alert(\"Gửi mail thất bạn cho tún roài huhu\");\r\n");
      out.write("				</script>\r\n");
      out.write("				\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				<div class=\"size-210 bor10 flex-w flex-col-m p-lr-93 p-tb-30 p-lr-15-lg w-full-md\">\r\n");
      out.write("					<div class=\"flex-w w-full p-b-42\">\r\n");
      out.write("						<span class=\"fs-18 cl5 txt-center size-211\">\r\n");
      out.write("							<span class=\"lnr lnr-map-marker\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"size-212 p-t-2\">\r\n");
      out.write("							<span class=\"mtext-110 cl2\">\r\n");
      out.write("								Địa chỉ\r\n");
      out.write("							</span>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"stext-115 cl6 size-213 p-t-18\">\r\n");
      out.write("								Trường Đại Học Công Nghiệp Hà Nội\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"flex-w w-full p-b-42\">\r\n");
      out.write("						<span class=\"fs-18 cl5 txt-center size-211\">\r\n");
      out.write("							<span class=\"lnr lnr-phone-handset\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"size-212 p-t-2\">\r\n");
      out.write("							<span class=\"mtext-110 cl2\">\r\n");
      out.write("								Số điện thoại\r\n");
      out.write("							</span>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"stext-115 cl1 size-213 p-t-18\">\r\n");
      out.write("								0376998401\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"flex-w w-full\">\r\n");
      out.write("						<span class=\"fs-18 cl5 txt-center size-211\">\r\n");
      out.write("							<span class=\"lnr lnr-envelope\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"size-212 p-t-2\">\r\n");
      out.write("							<span class=\"mtext-110 cl2\">\r\n");
      out.write("								Thư điện tử\r\n");
      out.write("							</span>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"stext-115 cl1 size-213 p-t-18\">\r\n");
      out.write("								ntuan4753@gmail.com\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- Map -->\r\n");
      out.write("	<!-- <div class=\"map\">\r\n");
      out.write("		<div class=\"size-303\" id=\"google_map\" data-map-x=\"40.691446\" data-map-y=\"-73.886787\" data-pin=\"images/icons/pin.png\" data-scrollwhell=\"0\" data-draggable=\"1\" data-zoom=\"11\"></div>\r\n");
      out.write("	</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("	<footer class=\"bg3 p-t-75 p-b-32\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">\r\n");
      out.write("						Danh mục\r\n");
      out.write("					</h4>\r\n");
      out.write("\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"p-b-10\">\r\n");
      out.write("							<a href=\"#\" class=\"stext-107 cl7 hov-cl1 trans-04\">\r\n");
      out.write("								Nữ\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\">\r\n");
      out.write("							<a href=\"#\" class=\"stext-107 cl7 hov-cl1 trans-04\">\r\n");
      out.write("								Nam\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\">\r\n");
      out.write("							<a href=\"#\" class=\"stext-107 cl7 hov-cl1 trans-04\">\r\n");
      out.write("								Giày\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\">\r\n");
      out.write("							<a href=\"#\" class=\"stext-107 cl7 hov-cl1 trans-04\">\r\n");
      out.write("								Đồng hồ\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">\r\n");
      out.write("						Trợ giúp\r\n");
      out.write("					</h4>\r\n");
      out.write("\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"p-b-10\">\r\n");
      out.write("							<a href=\"#\" class=\"stext-107 cl7 hov-cl1 trans-04\">\r\n");
      out.write("								Theo dõi đơn\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\">\r\n");
      out.write("							<a href=\"#\" class=\"stext-107 cl7 hov-cl1 trans-04\">\r\n");
      out.write("								Hoàn trả \r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\">\r\n");
      out.write("							<a href=\"#\" class=\"stext-107 cl7 hov-cl1 trans-04\">\r\n");
      out.write("								Giao hàng\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\">\r\n");
      out.write("							<a href=\"#\" class=\"stext-107 cl7 hov-cl1 trans-04\">\r\n");
      out.write("								FAQs\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">\r\n");
      out.write("						LIÊN LẠC\r\n");
      out.write("					</h4>\r\n");
      out.write("\r\n");
      out.write("					<p class=\"stext-107 cl7 size-201\">\r\n");
      out.write("						Có bất kì câu hỏi nào? Hãy đến cửa hàng chúng tôi tại 8th floor, 379 Hudson St, New York, NY 10018 hoặc gọi đến số (+84) 96 716 6879\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"p-t-27\">\r\n");
      out.write("						<a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\">\r\n");
      out.write("							<i class=\"fa fa-facebook\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("						<a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\">\r\n");
      out.write("							<i class=\"fa fa-instagram\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("						<a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\">\r\n");
      out.write("							<i class=\"fa fa-pinterest-p\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">\r\n");
      out.write("						Đăng ký nhận thông báo\r\n");
      out.write("					</h4>\r\n");
      out.write("\r\n");
      out.write("					<form>\r\n");
      out.write("						<div class=\"wrap-input1 w-full p-b-4\">\r\n");
      out.write("							<input class=\"input1 bg-none plh1 stext-107 cl7\" type=\"text\" name=\"email\" placeholder=\"email@example.com\">\r\n");
      out.write("							<div class=\"focus-input1 trans-04\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"p-t-18\">\r\n");
      out.write("							<button class=\"flex-c-m stext-101 cl0 size-103 bg1 bor1 hov-btn2 p-lr-15 trans-04\">\r\n");
      out.write("								Đăng kí\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"p-t-40\">\r\n");
      out.write("				<div class=\"flex-c-m flex-w p-b-18\">\r\n");
      out.write("					<a href=\"#\" class=\"m-all-1\">\r\n");
      out.write("						<img src=\"images/icons/icon-pay-01.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<a href=\"#\" class=\"m-all-1\">\r\n");
      out.write("						<img src=\"images/icons/icon-pay-02.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<a href=\"#\" class=\"m-all-1\">\r\n");
      out.write("						<img src=\"images/icons/icon-pay-03.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<a href=\"#\" class=\"m-all-1\">\r\n");
      out.write("						<img src=\"images/icons/icon-pay-04.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<a href=\"#\" class=\"m-all-1\">\r\n");
      out.write("						<img src=\"images/icons/icon-pay-05.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<p class=\"stext-107 cl6 txt-center\">\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a> &amp; distributed by <a href=\"https://themewagon.com\" target=\"_blank\">ThemeWagon</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Back to top -->\r\n");
      out.write("	<div class=\"btn-back-to-top\" id=\"myBtn\">\r\n");
      out.write("		<span class=\"symbol-btn-back-to-top\">\r\n");
      out.write("			<i class=\"zmdi zmdi-chevron-up\"></i>\r\n");
      out.write("		</span>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("<!--===============================================================================================-->	\r\n");
      out.write("	<script src=\"vendor/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/animsition/js/animsition.min.js\"></script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/bootstrap/js/popper.js\"></script>\r\n");
      out.write("	<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/select2/select2.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\".js-select2\").each(function(){\r\n");
      out.write("			$(this).select2({\r\n");
      out.write("				minimumResultsForSearch: 20,\r\n");
      out.write("				dropdownParent: $(this).next('.dropDownSelect2')\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/MagnificPopup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/perfect-scrollbar/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.js-pscroll').each(function(){\r\n");
      out.write("			$(this).css('position','relative');\r\n");
      out.write("			$(this).css('overflow','hidden');\r\n");
      out.write("			var ps = new PerfectScrollbar(this, {\r\n");
      out.write("				wheelSpeed: 1,\r\n");
      out.write("				scrollingThreshold: 1000,\r\n");
      out.write("				wheelPropagation: false,\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(window).on('resize', function(){\r\n");
      out.write("				ps.update();\r\n");
      out.write("			})\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyAKFWBqlKAGCeS1rMVoaNlwyayu0e0YRes\"></script>\r\n");
      out.write("	<script src=\"js/map-custom.js\"></script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
