/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2024-12-23 08:41:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.User;
import model.GioHang;
import Reponsitory.Laydulieuchonguoidung;
import model.DanhMuc;
import model.SanPham;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("model.GioHang");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("Reponsitory.Laydulieuchonguoidung");
    _jspx_imports_classes.add("model.SanPham");
    _jspx_imports_classes.add("model.DanhMuc");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Trang chủ</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"assetsquantri/img/logo.png\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"fonts/iconic/css/material-design-iconic-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"fonts/linearicons-v1.0.0/icon-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animate/animate.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/select2/select2.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/slick/slick.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/MagnificPopup/magnific-popup.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/perfect-scrollbar/perfect-scrollbar.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/util.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+Vietnamese&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<style >\r\n");
      out.write(".icon-header-dropdown {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("    display: none; /* Ẩn menu mặc định */\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 100%;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul li {\r\n");
      out.write("    padding: 8px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul li a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-header-dropdown:hover .dropdown-menu {\r\n");
      out.write("    display: block; /* Hiển thị menu khi hover */\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("            font-family: 'Noto Sans Vietnamese', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Tùy chỉnh màu và kiểu chữ cho tiêu đề */\r\n");
      out.write("        .custom-title {\r\n");
      out.write("            font-size: 2.5rem; /* Điều chỉnh kích thước chữ */\r\n");
      out.write("            font-weight: bold; /* Đặt chữ đậm */\r\n");
      out.write("            /* color: #000000; /* Màu đen */ */\r\n");
      out.write("            text-align: center; /* Căn giữa */\r\n");
      out.write("            margin-top: 20px; /* Thêm khoảng cách phía trên */\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"animsition\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	<header class=\"header-v4\">\r\n");
      out.write("		<!-- Header desktop -->\r\n");
      out.write("		<div class=\"container-menu-desktop\">\r\n");
      out.write("			<!-- Topbar -->\r\n");
      out.write("			<div class=\"top-bar\">\r\n");
      out.write("				<div class=\"content-topbar flex-sb-m h-full container\">\r\n");
      out.write("					<div class=\"left-top-bar\">Trang web bán hàng thời trang nhóm 17\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"wrap-menu-desktop how-shadow1\">\r\n");
      out.write("				<nav class=\"limiter-menu-desktop container\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Logo desktop -->\r\n");
      out.write("					<a href=\"Laydulieusanpham\" class=\"logo\"> <img src=\"assetsquantri/img/logo.png\"\r\n");
      out.write("						alt=\"IMG-LOGO\">\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<!-- Menu desktop -->\r\n");
      out.write("					<div class=\"menu-desktop\">\r\n");
      out.write("						<ul class=\"main-menu\">\r\n");
      out.write("							<li class=\"active-menu\"><a href=\"Laydulieusanpham\">Trang\r\n");
      out.write("									chủ</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"Cuahang\">Cửa hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"label1\" data-label1=\"hot\"><a href=\"Giohang\">Giỏ\r\n");
      out.write("									hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"blog.jsp\">Blog</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"about.jsp\">Giới thiệu</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"contact.jsp\">Liên hệ</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- Icon header -->\r\n");
      out.write("					<div class=\"wrap-icon-header flex-w flex-r-m\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search\">\r\n");
      out.write("							<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div\r\n");
      out.write("							");
Laydulieuchonguoidung lgn = new Laydulieuchonguoidung();
List<GioHang> gh = lgn.LayHetThongTinGioHang();
HttpSession tk = request.getSession(false);
List<User> user = (List<User>) tk.getAttribute("Ghinhotaikhoan");
int soluong = 0;
float tongTien = 0;
if (user != null) {
	for (GioHang gioHang : gh) {
		for (User u : user)
			if (u.getMaTaiKhoan() == gioHang.getMaNguoiDung()) {
				soluong += gioHang.getSoLuong();
				tongTien += gioHang.getGia();
			}
	}

}
      out.write("\r\n");
      out.write("							class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart\"\r\n");
      out.write("							data-notify=\"");
      out.print(soluong);
      out.write("\">\r\n");
      out.write("							<i class=\"zmdi zmdi-shopping-cart\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"icon-header-dropdown\">\r\n");
      out.write("							<a href=\"#\"\r\n");
      out.write("								class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11\">\r\n");
      out.write("								<i class=\"fa fa-user\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							<!-- Thẻ con chứa thông tin cá nhân và đơn hàng -->\r\n");
      out.write("							<div class=\"dropdown-menu\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"Thongtincanhan.jsp\">Thông tin cá nhân</a></li>\r\n");
      out.write("									<li><a href=\"Thongtindonhangdamua.jsp\">Đơn hàng</a></li>\r\n");
      out.write("									<li><a href=\"Dangxuat\">Đăng xuất</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Header Mobile -->\r\n");
      out.write("		<div class=\"wrap-header-mobile\">\r\n");
      out.write("			<!-- Logo moblie -->\r\n");
      out.write("			<div class=\"logo-mobile\">\r\n");
      out.write("				<a href=\"index.html\"><img src=\"images/icons/logo-01.png\"\r\n");
      out.write("					alt=\"IMG-LOGO\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Icon header -->\r\n");
      out.write("			<div class=\"wrap-icon-header flex-w flex-r-m\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search\">\r\n");
      out.write("							<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");

if (user != null) {
	for (GioHang gioHang : gh) {
		for (User u : user)
			if (u.getMaTaiKhoan() == gioHang.getMaNguoiDung()) {
				soluong += gioHang.getSoLuong();
				tongTien += gioHang.getGia();
			}
	}

}
      out.write("\r\n");
      out.write("						<div\r\n");
      out.write("							\r\n");
      out.write("							class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart\"\r\n");
      out.write("							data-notify=\"");
      out.print(soluong);
      out.write("\">\r\n");
      out.write("							<i class=\"zmdi zmdi-shopping-cart\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"icon-header-dropdown\">\r\n");
      out.write("							<a href=\"#\"\r\n");
      out.write("								class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11\">\r\n");
      out.write("								<i class=\"fa fa-user\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							<!-- Thẻ con chứa thông tin cá nhân và đơn hàng -->\r\n");
      out.write("							<div class=\"dropdown-menu\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"Thongtincanhan.jsp\">Thông tin cá nhân</a></li>\r\n");
      out.write("									<li><a href=\"Thongtindonhangdamua.jsp\">Đơn hàng</a></li>\r\n");
      out.write("									<li><a href=\"Dangxuat\">Đăng xuất</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Button show menu -->\r\n");
      out.write("			<div class=\"btn-show-menu-mobile hamburger hamburger--squeeze\">\r\n");
      out.write("				<span class=\"hamburger-box\"> <span class=\"hamburger-inner\"></span>\r\n");
      out.write("				</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Menu Mobile -->\r\n");
      out.write("		<div class=\"menu-mobile\">\r\n");
      out.write("			<ul class=\"topbar-mobile\">\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"left-top-bar\">Miễn phí giao hàng cho đơn từ $100\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"right-top-bar flex-w h-full\">\r\n");
      out.write("						<a href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> Trợ giúp & FAQs\r\n");
      out.write("						</a> <a href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> Tài khoản của\r\n");
      out.write("							tôi </a> <a href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> VN </a> <a\r\n");
      out.write("							href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> USD </a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"main-menu-m\">\r\n");
      out.write("				<li><a href=\"Laydanhmucsanpham\">Trang chủ</a> <span\r\n");
      out.write("					class=\"arrow-main-menu-m\"> <i class=\"fa fa-angle-right\"\r\n");
      out.write("						aria-hidden=\"true\"></i>\r\n");
      out.write("				</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"Cuahang\">Cửa hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"Giohang\" class=\"label1 rs1\" data-label1=\"hot\">Giỏ\r\n");
      out.write("						hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"blog.jsp\">Blog</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"about.jsp\">Giới thiệu</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"contact.jsp\">Liên hệ</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal Search -->\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"modal-search-header flex-c-m trans-04 js-hide-modal-search\">\r\n");
      out.write("			<div class=\"container-search-header\">\r\n");
      out.write("				<button\r\n");
      out.write("					class=\"flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search\">\r\n");
      out.write("					<img src=\"images/icons/icon-close2.png\" alt=\"CLOSE\">\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<form class=\"wrap-search-header flex-w p-l-15\">\r\n");
      out.write("					<button class=\"flex-c-m trans-04\">\r\n");
      out.write("						<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("					<input class=\"plh3\" type=\"text\" name=\"search\"\r\n");
      out.write("						placeholder=\"Search...\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<!-- Cart -->\r\n");
      out.write("	<div class=\"wrap-header-cart js-panel-cart\">\r\n");
      out.write("		<div class=\"s-full js-hide-cart\"></div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"header-cart flex-col-l p-l-65 p-r-25\">\r\n");
      out.write("			<div class=\"header-cart-title flex-w flex-sb-m p-b-8\">\r\n");
      out.write("				<span class=\"mtext-103 cl2\"> Giỏ hàng </span>\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart\">\r\n");
      out.write("					<i class=\"zmdi zmdi-close\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"header-cart-content flex-w js-pscroll\">\r\n");
      out.write("				<ul class=\"header-cart-wrapitem w-full\">\r\n");
      out.write("					");

					if (user != null) {
						for (GioHang giohang : gh) {
							for (User u : user) {
						if (u.getMaTaiKhoan() == giohang.getMaNguoiDung()) {
					
      out.write("\r\n");
      out.write("					<li class=\"header-cart-item flex-w flex-t m-b-12\">\r\n");
      out.write("						<div class=\"header-cart-item-img\">\r\n");
      out.write("							<img src=\"");
      out.print(giohang.getDuongDan());
      out.write("\" alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"header-cart-item-txt p-t-8\">\r\n");
      out.write("							<a href=\"#\" class=\"header-cart-item-name m-b-18 hov-cl1 trans-04\">\r\n");
      out.write("								White Shirt Pleat </a> <span class=\"header-cart-item-info\"> ");
      out.print(giohang.getSoLuong());
      out.write("\r\n");
      out.write("								x $");
      out.print(giohang.getGia());
      out.write("\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					");

					}
					}
					}
					}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"w-full\">\r\n");
      out.write("					<div class=\"header-cart-total w-full p-tb-40\">\r\n");
      out.write("						Tổng tiền: $");
      out.print(tongTien);
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"header-cart-buttons flex-w w-full\">\r\n");
      out.write("						<a href=\"Giohang\"\r\n");
      out.write("							class=\"flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10\">\r\n");
      out.write("							Xem giỏ hàng </a> <a href=\"Giohang\"\r\n");
      out.write("							class=\"flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10\">\r\n");
      out.write("							Kiểm tra </a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Slider -->\r\n");
      out.write("	<section class=\"section-slide\">\r\n");
      out.write("		<div class=\"wrap-slick1\">\r\n");
      out.write("			<div class=\"slick1\">\r\n");
      out.write("				<div class=\"item-slick1\"\r\n");
      out.write("					style=\"background-image: url(images/slide-01.jpg);\">\r\n");
      out.write("					<div class=\"container h-full\">\r\n");
      out.write("						<div class=\"flex-col-l-m h-full p-t-100 p-b-30 respon5\">\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"fadeInDown\" data-delay=\"0\">\r\n");
      out.write("								<span class=\"ltext-101 cl2 respon2\"> Women Collection\r\n");
      out.write("									2018 </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"fadeInUp\" data-delay=\"800\">\r\n");
      out.write("								<h2 class=\"ltext-201 cl2 p-t-19 p-b-43 respon1\">NEW SEASON\r\n");
      out.write("								</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"zoomIn\" data-delay=\"1600\">\r\n");
      out.write("								<a href=\"Cuahang\"\r\n");
      out.write("									class=\"flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04\">\r\n");
      out.write("									Mua ngay </a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"item-slick1\"\r\n");
      out.write("					style=\"background-image: url(images/slide-02.jpg);\">\r\n");
      out.write("					<div class=\"container h-full\">\r\n");
      out.write("						<div class=\"flex-col-l-m h-full p-t-100 p-b-30 respon5\">\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"rollIn\" data-delay=\"0\">\r\n");
      out.write("								<span class=\"ltext-101 cl2 respon2\"> Men New-Season </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"lightSpeedIn\" data-delay=\"800\">\r\n");
      out.write("								<h2 class=\"ltext-201 cl2 p-t-19 p-b-43 respon1\">Jackets &\r\n");
      out.write("									Coats</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"slideInUp\" data-delay=\"1600\">\r\n");
      out.write("								<a href=\"product.html\"\r\n");
      out.write("									class=\"flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04\">\r\n");
      out.write("									Mua ngay </a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"item-slick1\"\r\n");
      out.write("					style=\"background-image: url(images/slide-03.jpg);\">\r\n");
      out.write("					<div class=\"container h-full\">\r\n");
      out.write("						<div class=\"flex-col-l-m h-full p-t-100 p-b-30 respon5\">\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"rotateInDownLeft\" data-delay=\"0\">\r\n");
      out.write("								<span class=\"ltext-101 cl2 respon2\"> Men Collection 2018\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"rotateInUpRight\" data-delay=\"800\">\r\n");
      out.write("								<h2 class=\"ltext-201 cl2 p-t-19 p-b-43 respon1\">New\r\n");
      out.write("									arrivals</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"rotateIn\" data-delay=\"1600\">\r\n");
      out.write("								<a href=\"product.html\"\r\n");
      out.write("									class=\"flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04\">\r\n");
      out.write("									Mua ngay </a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Banner -->\r\n");
      out.write("	<div class=\"sec-banner bg0 p-t-80 p-b-50\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-6 col-xl-4 p-b-30 m-lr-auto\">\r\n");
      out.write("					<!-- Block1 -->\r\n");
      out.write("					<div class=\"block1 wrap-pic-w\">\r\n");
      out.write("						<img src=\"images/banner-01.jpg\" alt=\"IMG-BANNER\"> <a\r\n");
      out.write("							href=\"Cuahang\"\r\n");
      out.write("							class=\"block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3\">\r\n");
      out.write("							<div class=\"block1-txt-child1 flex-col-l\">\r\n");
      out.write("								<span class=\"block1-name ltext-102 trans-04 p-b-8\"> Nữ </span> <span\r\n");
      out.write("									class=\"block1-info stext-102 trans-04\"> 2024 </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block1-txt-child2 p-b-4 trans-05\">\r\n");
      out.write("								<div class=\"block1-link stext-101 cl0 trans-09\">Cửa hàng</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6 col-xl-4 p-b-30 m-lr-auto\">\r\n");
      out.write("					<!-- Block1 -->\r\n");
      out.write("					<div class=\"block1 wrap-pic-w\">\r\n");
      out.write("						<img src=\"images/banner-02.jpg\" alt=\"IMG-BANNER\"> <a\r\n");
      out.write("							href=\"Cuahang\"\r\n");
      out.write("							class=\"block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3\">\r\n");
      out.write("							<div class=\"block1-txt-child1 flex-col-l\">\r\n");
      out.write("								<span class=\"block1-name ltext-102 trans-04 p-b-8\"> Nam </span>\r\n");
      out.write("\r\n");
      out.write("								<span class=\"block1-info stext-102 trans-04\"> 2024 </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block1-txt-child2 p-b-4 trans-05\">\r\n");
      out.write("								<div class=\"block1-link stext-101 cl0 trans-09\">Cửa hàng</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6 col-xl-4 p-b-30 m-lr-auto\">\r\n");
      out.write("					<!-- Block1 -->\r\n");
      out.write("					<div class=\"block1 wrap-pic-w\">\r\n");
      out.write("						<img src=\"images/banner-03.jpg\" alt=\"IMG-BANNER\"> <a\r\n");
      out.write("							href=\"Cuahang\"\r\n");
      out.write("							class=\"block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3\">\r\n");
      out.write("							<div class=\"block1-txt-child1 flex-col-l\">\r\n");
      out.write("								<span class=\"block1-name ltext-102 trans-04 p-b-8\"> Phụ\r\n");
      out.write("									kiện </span> <span class=\"block1-info stext-102 trans-04\"> Xu\r\n");
      out.write("									hướng mới </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block1-txt-child2 p-b-4 trans-05\">\r\n");
      out.write("								<div class=\"block1-link stext-101 cl0 trans-09\">Cửa hàng</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Product -->\r\n");
      out.write("	<section class=\"bg0 p-t-23 p-b-140\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"p-b-10\">\r\n");
      out.write("				<!-- <p class=\"custom-title\">Tổng quan sản phẩm</p> -->\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"flex-w flex-sb-m p-b-52\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				");

				List<DanhMuc> listDanhMuc = (List<DanhMuc>) request.getAttribute("listDanhMuc");
				
      out.write("\r\n");
      out.write("				<div class=\"flex-w flex-l-m filter-tope-group m-tb-10\">\r\n");
      out.write("					<button\r\n");
      out.write("						class=\"stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1\"\r\n");
      out.write("						data-filter=\"*\">Tất cả</button>\r\n");
      out.write("					");

					for (DanhMuc d : listDanhMuc) {
					
      out.write("\r\n");
      out.write("					<button class=\"stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5\"\r\n");
      out.write("						data-filter=\".");
      out.print(d.getTenDanhMuc());
      out.write("\">\r\n");
      out.write("						");
      out.print(d.getTenDanhMuc());
      out.write("\r\n");
      out.write("					</button>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"flex-w flex-c-m m-tb-10\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search\">\r\n");
      out.write("						<i class=\"icon-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-search\"></i>\r\n");
      out.write("						<i\r\n");
      out.write("							class=\"icon-close-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none\"></i>\r\n");
      out.write("						Tìm kiếm\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Search product -->\r\n");
      out.write("				<div class=\"dis-none panel-search w-full p-t-10 p-b-15\">\r\n");
      out.write("					<form action=\"Timkiemsanpham\" method=\"post\">\r\n");
      out.write("						<div class=\"bor8 dis-flex p-l-15\">\r\n");
      out.write("							<button class=\"size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04\">\r\n");
      out.write("								<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("							</button>\r\n");
      out.write("\r\n");
      out.write("							<input class=\"mtext-107 cl2 size-114 plh2 p-r-15\" type=\"text\"\r\n");
      out.write("								name=\"timKiem\" placeholder=\"Tìm kiếm\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Filter -->\r\n");
      out.write("				<div class=\"dis-none panel-filter w-full p-t-10\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"wrap-filter flex-w bg6 w-full p-lr-40 p-t-27 p-lr-15-sm\">\r\n");
      out.write("						<div class=\"filter-col1 p-r-15 p-b-27\">\r\n");
      out.write("							<div class=\"mtext-102 cl2 p-b-15\">Sắp xếp theo</div>\r\n");
      out.write("\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> Mặc định </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> Sự phổ biến </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> Đánh giá trung bình\r\n");
      out.write("								</a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04 filter-link-active\">\r\n");
      out.write("										Sự mới mẻ </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> Giá: Thấp đến Cao </a>\r\n");
      out.write("								</li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> Giá: Cao đến Thấp </a>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"filter-col2 p-r-15 p-b-27\">\r\n");
      out.write("							<div class=\"mtext-102 cl2 p-b-15\">Giá</div>\r\n");
      out.write("\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04 filter-link-active\">\r\n");
      out.write("										Tất cả </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> $0.00 - $50.00 </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> $50.00 - $100.00 </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> $100.00 - $150.00 </a>\r\n");
      out.write("								</li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> $150.00 - $200.00 </a>\r\n");
      out.write("								</li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> $200.00+ </a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"filter-col3 p-r-15 p-b-27\">\r\n");
      out.write("							<div class=\"mtext-102 cl2 p-b-15\">Màu</div>\r\n");
      out.write("\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #222;\"> <i class=\"zmdi zmdi-circle\"></i>\r\n");
      out.write("								</span> <a href=\"#\" class=\"filter-link stext-106 trans-04\"> Đen </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #4272d7;\"> <i class=\"zmdi zmdi-circle\"></i>\r\n");
      out.write("								</span> <a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04 filter-link-active\">\r\n");
      out.write("										Xanh </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #b3b3b3;\"> <i class=\"zmdi zmdi-circle\"></i>\r\n");
      out.write("								</span> <a href=\"#\" class=\"filter-link stext-106 trans-04\"> Xám </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #00ad5f;\"> <i class=\"zmdi zmdi-circle\"></i>\r\n");
      out.write("								</span> <a href=\"#\" class=\"filter-link stext-106 trans-04\"> Xanh lá\r\n");
      out.write("								</a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #fa4251;\"> <i class=\"zmdi zmdi-circle\"></i>\r\n");
      out.write("								</span> <a href=\"#\" class=\"filter-link stext-106 trans-04\"> Đỏ </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #aaa;\"> <i class=\"zmdi zmdi-circle-o\"></i>\r\n");
      out.write("								</span> <a href=\"#\" class=\"filter-link stext-106 trans-04\"> Trắng </a>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"filter-col4 p-b-27\">\r\n");
      out.write("							<div class=\"mtext-102 cl2 p-b-15\">Tags</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"flex-w p-t-4 m-r--5\">\r\n");
      out.write("								<a href=\"#\"\r\n");
      out.write("									class=\"flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5\">\r\n");
      out.write("									Fashion </a> <a href=\"#\"\r\n");
      out.write("									class=\"flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5\">\r\n");
      out.write("									Lifestyle </a> <a href=\"#\"\r\n");
      out.write("									class=\"flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5\">\r\n");
      out.write("									Denim </a> <a href=\"#\"\r\n");
      out.write("									class=\"flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5\">\r\n");
      out.write("									Streetstyle </a> <a href=\"#\"\r\n");
      out.write("									class=\"flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5\">\r\n");
      out.write("									Crafts </a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row isotope-grid\">\r\n");
      out.write("				");

				List<SanPham> list = (List<SanPham>) request.getAttribute("listHome");

				for (SanPham sp : list) {
					for (DanhMuc d : listDanhMuc) {
						if (sp.getMaDanhMuc() == d.getMaDanhmuc()) {
				
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item ");
      out.print(d.getTenDanhMuc());
      out.write("\">\r\n");
      out.write("					");

					}
					}
					
      out.write("\r\n");
      out.write("					<!-- Block2 -->\r\n");
      out.write("					<div class=\"block2\">\r\n");
      out.write("						<div class=\"block2-pic hov-img0\">\r\n");
      out.write("							<img src=\"");
      out.print(sp.getDuongDanAnh());
      out.write("\" alt=\"IMG-PRODUCT\"\r\n");
      out.write("								style=\"height: 300px;\"> <a\r\n");
      out.write("								href=\"Giohangproducttail?id=");
      out.print(sp.getMaSanpham());
      out.write("\"\r\n");
      out.write("								class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 \">\r\n");
      out.write("								Xem nhanh </a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
      out.write("							<div class=\"block2-txt-child1 flex-col-l \">\r\n");
      out.write("								<a href=\"Giohangproducttail?id=");
      out.print(sp.getMaSanpham());
      out.write("\"\r\n");
      out.write("									class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\"> ");
      out.print(sp.getTenSanPham());
      out.write("\r\n");
      out.write("								</a> <span class=\"stext-105 cl3\"> ");
      out.print(sp.getGia());
      out.write("\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
      out.write("								<a href=\"#\"\r\n");
      out.write("									class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
      out.write("									<img class=\"icon-heart1 dis-block trans-04\"\r\n");
      out.write("									src=\"images/icons/icon-heart-01.png\" alt=\"ICON\"> <img\r\n");
      out.write("									class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
      out.write("									src=\"images/icons/icon-heart-02.png\" alt=\"ICON\">\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Load more -->\r\n");
      out.write("			<div class=\"flex-c-m flex-w w-full p-t-45\">\r\n");
      out.write("				<a href=\"Cuahang\"\r\n");
      out.write("					class=\"flex-c-m stext-101 cl5 size-103 bg2 bor1 hov-btn1 p-lr-15 trans-04\">\r\n");
      out.write("					Xem thêm </a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<footer class=\"bg3 p-t-75 p-b-32\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">Danh mục</h4>\r\n");
      out.write("\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Nữ </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Nam </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Giày </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Đồng hồ </a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">Trợ giúp</h4>\r\n");
      out.write("\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Theo dõi đơn </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Hoàn trả </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Giao hàng </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> FAQs </a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">LIÊN LẠC</h4>\r\n");
      out.write("\r\n");
      out.write("					<p class=\"stext-107 cl7 size-201\">Có bất kì câu hỏi nào? Hãy\r\n");
      out.write("						đến cửa hàng chúng tôi tại 8th floor, 379 Hudson St, New York, NY\r\n");
      out.write("						10018 hoặc gọi đến số (+84) 96 716 6879</p>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"p-t-27\">\r\n");
      out.write("						<a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\"> <i\r\n");
      out.write("							class=\"fa fa-facebook\"></i>\r\n");
      out.write("						</a> <a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\"> <i\r\n");
      out.write("							class=\"fa fa-instagram\"></i>\r\n");
      out.write("						</a> <a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\"> <i\r\n");
      out.write("							class=\"fa fa-pinterest-p\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">Đăng ký nhận thông báo</h4>\r\n");
      out.write("\r\n");
      out.write("					<form>\r\n");
      out.write("						<div class=\"wrap-input1 w-full p-b-4\">\r\n");
      out.write("							<input class=\"input1 bg-none plh1 stext-107 cl7\" type=\"text\"\r\n");
      out.write("								name=\"email\" placeholder=\"email@example.com\">\r\n");
      out.write("							<div class=\"focus-input1 trans-04\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"p-t-18\">\r\n");
      out.write("							<button\r\n");
      out.write("								class=\"flex-c-m stext-101 cl0 size-103 bg1 bor1 hov-btn2 p-lr-15 trans-04\">\r\n");
      out.write("								Đăng kí</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"p-t-40\">\r\n");
      out.write("				<div class=\"flex-c-m flex-w p-b-18\">\r\n");
      out.write("					<a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-01.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-02.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-03.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-04.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-05.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<p class=\"stext-107 cl6 txt-center\">\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					Copyright &copy;\r\n");
      out.write("					<script>\r\n");
      out.write("						document.write(new Date().getFullYear());\r\n");
      out.write("					</script>\r\n");
      out.write("					All rights reserved | Made with <i class=\"fa fa-heart-o\"\r\n");
      out.write("						aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\"\r\n");
      out.write("						target=\"_blank\">Colorlib</a> &amp; distributed by <a\r\n");
      out.write("						href=\"https://themewagon.com\" target=\"_blank\">ThemeWagon</a>\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Back to top -->\r\n");
      out.write("	<div class=\"btn-back-to-top\" id=\"myBtn\">\r\n");
      out.write("		<span class=\"symbol-btn-back-to-top\"> <i\r\n");
      out.write("			class=\"zmdi zmdi-chevron-up\"></i>\r\n");
      out.write("		</span>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/animsition/js/animsition.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/bootstrap/js/popper.js\"></script>\r\n");
      out.write("	<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/select2/select2.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\".js-select2\").each(function() {\r\n");
      out.write("			$(this).select2({\r\n");
      out.write("				minimumResultsForSearch : 20,\r\n");
      out.write("				dropdownParent : $(this).next('.dropDownSelect2')\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/daterangepicker/moment.min.js\"></script>\r\n");
      out.write("	<script src=\"vendor/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/slick/slick.min.js\"></script>\r\n");
      out.write("	<script src=\"js/slick-custom.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/parallax100/parallax100.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.parallax100').parallax100();\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/MagnificPopup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.gallery-lb').each(function() { // the containers for all your galleries\r\n");
      out.write("			$(this).magnificPopup({\r\n");
      out.write("				delegate : 'a', // the selector for gallery item\r\n");
      out.write("				type : 'image',\r\n");
      out.write("				gallery : {\r\n");
      out.write("					enabled : true\r\n");
      out.write("				},\r\n");
      out.write("				mainClass : 'mfp-fade'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/isotope/isotope.pkgd.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/sweetalert/sweetalert.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.js-addwish-b2').on('click', function(e) {\r\n");
      out.write("			e.preventDefault();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$('.js-addwish-b2').each(\r\n");
      out.write("				function() {\r\n");
      out.write("					var nameProduct = $(this).parent().parent().find(\r\n");
      out.write("							'.js-name-b2').html();\r\n");
      out.write("					$(this).on('click', function() {\r\n");
      out.write("						swal(nameProduct, \"is added to wishlist !\", \"success\");\r\n");
      out.write("\r\n");
      out.write("						$(this).addClass('js-addedwish-b2');\r\n");
      out.write("						$(this).off('click');\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("		$('.js-addwish-detail').each(\r\n");
      out.write("				function() {\r\n");
      out.write("					var nameProduct = $(this).parent().parent().parent().find(\r\n");
      out.write("							'.js-name-detail').html();\r\n");
      out.write("\r\n");
      out.write("					$(this).on('click', function() {\r\n");
      out.write("						swal(nameProduct, \"is added to wishlist !\", \"success\");\r\n");
      out.write("\r\n");
      out.write("						$(this).addClass('js-addedwish-detail');\r\n");
      out.write("						$(this).off('click');\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("		/*---------------------------------------------*/\r\n");
      out.write("\r\n");
      out.write("		$('.js-addcart-detail').each(\r\n");
      out.write("				function() {\r\n");
      out.write("					var nameProduct = $(this).parent().parent().parent()\r\n");
      out.write("							.parent().find('.js-name-detail').html();\r\n");
      out.write("					$(this).on('click', function() {\r\n");
      out.write("						swal(nameProduct, \"is added to cart !\", \"success\");\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/perfect-scrollbar/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.js-pscroll').each(function() {\r\n");
      out.write("			$(this).css('position', 'relative');\r\n");
      out.write("			$(this).css('overflow', 'hidden');\r\n");
      out.write("			var ps = new PerfectScrollbar(this, {\r\n");
      out.write("				wheelSpeed : 1,\r\n");
      out.write("				scrollingThreshold : 1000,\r\n");
      out.write("				wheelPropagation : false,\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(window).on('resize', function() {\r\n");
      out.write("				ps.update();\r\n");
      out.write("			})\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
