/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2024-12-23 04:45:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Danhgia;
import model.DonHang;
import model.User;
import model.GioHang;
import controller.Donhang;
import Reponsitory.Laydulieuchonguoidung;
import model.ChiTietSanPham;
import model.SanPham;
import java.util.List;

public final class product_002ddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(12);
    _jspx_imports_classes.add("model.GioHang");
    _jspx_imports_classes.add("model.Danhgia");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.ChiTietSanPham");
    _jspx_imports_classes.add("model.DonHang");
    _jspx_imports_classes.add("controller.Donhang");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("Reponsitory.Laydulieuchonguoidung");
    _jspx_imports_classes.add("model.SanPham");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Product Detail</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"assetsquantri/img/logo.png\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"fonts/iconic/css/material-design-iconic-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"fonts/linearicons-v1.0.0/icon-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animate/animate.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/select2/select2.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/slick/slick.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/MagnificPopup/magnific-popup.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/perfect-scrollbar/perfect-scrollbar.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/util.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<style>\r\n");
      out.write("/* Tạo một container flexbox cho nút */\r\n");
      out.write(".button-group {\r\n");
      out.write("	display: flex; /* Sử dụng flexbox để căn chỉnh */\r\n");
      out.write("	gap: 15px; /* Tạo khoảng cách đều giữa các nút */\r\n");
      out.write("	/* Khi màn hình nhỏ, các nút sẽ xuống dòng */\r\n");
      out.write("	justify-content: flex-start; /* Canh trái các nút */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nút \"Thêm vào giỏ hàng\" */\r\n");
      out.write(".js-addcart-detail {\r\n");
      out.write("	background-color: #28a745; /* Màu xanh lá */\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	padding: 12px 25px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	width: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js-addcart-detail i {\r\n");
      out.write("	margin-right: 8px; /* Khoảng cách giữa biểu tượng và chữ */\r\n");
      out.write("	font-size: 20px; /* Kích thước biểu tượng */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nút \"Đặt hàng\" */\r\n");
      out.write(".js-order {\r\n");
      out.write("	background-color: #007bff; /* Màu xanh dương */\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	padding: 12px 25px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	width: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js-order i {\r\n");
      out.write("	margin-right: 8px; /* Khoảng cách giữa biểu tượng và chữ */\r\n");
      out.write("	font-size: 20px; /* Kích thước biểu tượng */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Hiệu ứng hover */\r\n");
      out.write(".js-addcart-detail:hover {\r\n");
      out.write("	background-color: #218838; /* Xanh lá đậm khi hover */\r\n");
      out.write("	transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".js-order:hover {\r\n");
      out.write("	background-color: #0056b3; /* Xanh dương đậm khi hover */\r\n");
      out.write("	transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive: Khi màn hình nhỏ hơn 768px, các nút sẽ tự động xuống dòng */\r\n");
      out.write("@media ( max-width : 768px) {\r\n");
      out.write("	.button-group {\r\n");
      out.write("		flex-direction: column; /* Xếp các nút theo chiều dọc */\r\n");
      out.write("		align-items: center; /* Canh giữa các nút */\r\n");
      out.write("	}\r\n");
      out.write("	.js-addcart-detail, .js-order {\r\n");
      out.write("		width: 100%; /* Chiếm toàn bộ chiều rộng của container */\r\n");
      out.write("		margin-bottom: 10px; /* Tạo khoảng cách giữa các nút */\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-header-dropdown {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("	display: none; /* Ẩn menu mặc định */\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 100%;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	z-index: 10;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul li {\r\n");
      out.write("	padding: 8px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul li a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-header-dropdown:hover .dropdown-menu {\r\n");
      out.write("	display: block; /* Hiển thị menu khi hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"animsition\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	<header class=\"header-v4\">\r\n");
      out.write("		<!-- Header desktop -->\r\n");
      out.write("		<div class=\"container-menu-desktop\">\r\n");
      out.write("			<!-- Topbar -->\r\n");
      out.write("			<div class=\"top-bar\">\r\n");
      out.write("				<div class=\"content-topbar flex-sb-m h-full container\">\r\n");
      out.write("					<div class=\"left-top-bar\">Trang web bán hàng thời trang nhóm 17</div>\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"wrap-menu-desktop how-shadow1\">\r\n");
      out.write("				<nav class=\"limiter-menu-desktop container\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Logo desktop -->\r\n");
      out.write("					<a href=\"#\" class=\"logo\"> <img src=\"assetsquantri/img/logo.png\"\r\n");
      out.write("						alt=\"IMG-LOGO\">\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<!-- Menu desktop -->\r\n");
      out.write("					<div class=\"menu-desktop\">\r\n");
      out.write("						<ul class=\"main-menu\">\r\n");
      out.write("							<li><a href=\"Laydulieusanpham\">Trang chủ</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"Cuahang\">Cửa hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"label1\" data-label1=\"hot\"><a href=\"Giohang\">Giỏ\r\n");
      out.write("									hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"blog.jsp\">Blog</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"about.jsp\">Giới thiệu</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"contact.jsp\">Liên hệ</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- Icon header -->\r\n");
      out.write("					<div class=\"wrap-icon-header flex-w flex-r-m\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search\">\r\n");
      out.write("							<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div\r\n");
      out.write("							");
Laydulieuchonguoidung lgn = new Laydulieuchonguoidung();
List<GioHang> gh = lgn.LayHetThongTinGioHang();
HttpSession tk = request.getSession(false);
List<User> user = (List<User>) tk.getAttribute("Ghinhotaikhoan");
int soluong = 0;
float tongTien = 0;
if (user != null) {
	for (GioHang gioHang : gh) {
		for (User u : user)
			if (u.getMaTaiKhoan() == gioHang.getMaNguoiDung()) {
				soluong += gioHang.getSoLuong();
				tongTien += gioHang.getGia();
			}
	}
}
      out.write("\r\n");
      out.write("							class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart\"\r\n");
      out.write("							data-notify=\"");
      out.print(soluong);
      out.write("\">\r\n");
      out.write("							<i class=\"zmdi zmdi-shopping-cart\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"icon-header-dropdown\">\r\n");
      out.write("							<a href=\"#\"\r\n");
      out.write("								class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11\">\r\n");
      out.write("								<i class=\"fa fa-user\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							<!-- Thẻ con chứa thông tin cá nhân và đơn hàng -->\r\n");
      out.write("							<div class=\"dropdown-menu\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"Thongtincanhan.jsp\">Thông tin cá nhân</a></li>\r\n");
      out.write("									<li><a href=\"Thongtindonhangdamua.jsp\">Đơn hàng</a></li>\r\n");
      out.write("									<li><a href=\"Dangxuat\">Đăng xuất</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Header Mobile -->\r\n");
      out.write("		<div class=\"wrap-header-mobile\">\r\n");
      out.write("			<!-- Logo moblie -->\r\n");
      out.write("			<div class=\"logo-mobile\">\r\n");
      out.write("				<a href=\"Laydulieuquantri\"><img src=\"assetsquantri/img/logo.png\"\r\n");
      out.write("					alt=\"IMG-LOGO\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Icon header -->\r\n");
      out.write("			<div class=\"wrap-icon-header flex-w flex-r-m m-r-15\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"icon-header-item cl2 hov-cl1 trans-04 p-r-11 js-show-modal-search\">\r\n");
      out.write("					<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti js-show-cart\"\r\n");
      out.write("					data-notify=\"2\">\r\n");
      out.write("					<i class=\"zmdi zmdi-shopping-cart\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<a href=\"#\"\r\n");
      out.write("					class=\"dis-block icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti\"\r\n");
      out.write("					data-notify=\"0\"> <i class=\"zmdi zmdi-favorite-outline\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Button show menu -->\r\n");
      out.write("			<div class=\"btn-show-menu-mobile hamburger hamburger--squeeze\">\r\n");
      out.write("				<span class=\"hamburger-box\"> <span class=\"hamburger-inner\"></span>\r\n");
      out.write("				</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Menu Mobile -->\r\n");
      out.write("		<div class=\"menu-mobile\">\r\n");
      out.write("			<ul class=\"topbar-mobile\">\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"left-top-bar\">Free shipping for standard order\r\n");
      out.write("						over $100</div>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"right-top-bar flex-w h-full\">\r\n");
      out.write("						<a href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> Help & FAQs </a> <a\r\n");
      out.write("							href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> My Account </a> <a\r\n");
      out.write("							href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> EN </a> <a href=\"#\"\r\n");
      out.write("							class=\"flex-c-m p-lr-10 trans-04\"> USD </a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"main-menu-m\">\r\n");
      out.write("				<li><a href=\"Laydulieusanpham\">Trang chủ</a> <span\r\n");
      out.write("					class=\"arrow-main-menu-m\"> <i class=\"fa fa-angle-right\"\r\n");
      out.write("						aria-hidden=\"true\"></i>\r\n");
      out.write("				</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"Cuahang\">Shop</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"Giohang\" class=\"label1 rs1\" data-label1=\"hot\">Giỏ\r\n");
      out.write("						hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"blog.jsp\">Blog</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"about.jsp\">About</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal Search -->\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"modal-search-header flex-c-m trans-04 js-hide-modal-search\">\r\n");
      out.write("			<div class=\"container-search-header\">\r\n");
      out.write("				<button\r\n");
      out.write("					class=\"flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search\">\r\n");
      out.write("					<img src=\"images/icons/icon-close2.png\" alt=\"CLOSE\">\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<form class=\"wrap-search-header flex-w p-l-15\">\r\n");
      out.write("					<button class=\"flex-c-m trans-04\">\r\n");
      out.write("						<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("					<input class=\"plh3\" type=\"text\" name=\"search\"\r\n");
      out.write("						placeholder=\"Search...\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<!-- Cart -->\r\n");
      out.write("	<div class=\"wrap-header-cart js-panel-cart\">\r\n");
      out.write("		<div class=\"s-full js-hide-cart\"></div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"header-cart flex-col-l p-l-65 p-r-25\">\r\n");
      out.write("			<div class=\"header-cart-title flex-w flex-sb-m p-b-8\">\r\n");
      out.write("				<span class=\"mtext-103 cl2\"> Giỏ hàng </span>\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart\">\r\n");
      out.write("					<i class=\"zmdi zmdi-close\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"header-cart-content flex-w js-pscroll\">\r\n");
      out.write("				<ul class=\"header-cart-wrapitem w-full\">\r\n");
      out.write("					");

					if (user != null) {
						for (GioHang giohang : gh) {
							for (User u : user) {
						if (u.getMaTaiKhoan() == giohang.getMaNguoiDung()) {
					
      out.write("\r\n");
      out.write("					<li class=\"header-cart-item flex-w flex-t m-b-12\">\r\n");
      out.write("						<div class=\"header-cart-item-img\">\r\n");
      out.write("							<img src=\"");
      out.print(giohang.getDuongDan());
      out.write("\" alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"header-cart-item-txt p-t-8\">\r\n");
      out.write("							<a href=\"#\" class=\"header-cart-item-name m-b-18 hov-cl1 trans-04\">\r\n");
      out.write("								White Shirt Pleat </a> <span class=\"header-cart-item-info\"> ");
      out.print(giohang.getSoLuong());
      out.write("\r\n");
      out.write("								x $");
      out.print(giohang.getGia());
      out.write("\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					");

					}
					}
					}
					}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"w-full\">\r\n");
      out.write("					<div class=\"header-cart-total w-full p-tb-40\">\r\n");
      out.write("						Tổng tiền: $");
      out.print(tongTien);
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"header-cart-buttons flex-w w-full\">\r\n");
      out.write("						<a href=\"Giohang\"\r\n");
      out.write("							class=\"flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10\">\r\n");
      out.write("							Xem giỏ hàng </a> <a href=\"Giohang\"\r\n");
      out.write("							class=\"flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10\">\r\n");
      out.write("							Kiểm tra </a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- breadcrumb -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<!-- <div class=\"bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg\">\r\n");
      out.write("			<a href=\"Laydulieusanpham\" class=\"stext-109 cl8 hov-cl1 trans-04\">\r\n");
      out.write("				Trang chủ <i class=\"fa fa-angle-right m-l-9 m-r-10\"\r\n");
      out.write("				aria-hidden=\"true\"></i>\r\n");
      out.write("			</a> <a href=\"#\" class=\"stext-109 cl8 hov-cl1 trans-04\">\r\n");
      out.write("				Men <i class=\"fa fa-angle-right m-l-9 m-r-10\" aria-hidden=\"true\"></i>\r\n");
      out.write("			</a> <span class=\"stext-109 cl4\"> Lightweight Jacket </span>\r\n");
      out.write("		</div> -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Product Detail -->\r\n");
      out.write("	<section class=\"sec-product-detail bg0 p-t-65 p-b-60\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				int id = (int) request.getAttribute("idSanPham");
				List<SanPham> listSP = (List<SanPham>) request.getAttribute("listSanPham");
				List<ChiTietSanPham> listCTSP = (List<ChiTietSanPham>) request.getAttribute("listChiTietSanPham");
				HttpSession s = request.getSession(false);
				String loi = (String) s.getAttribute("loiTonTai");
				System.out.println("Giá trị loiTonTai: " + s.getAttribute("loiTonTai"));
				String loiDanhGia = (String) s.getAttribute("Loidanhgia");
				if (loi != null && !loi.isEmpty()) {
					session.removeAttribute("loiTonTai"); // Xóa sau khi hiển thị
				
      out.write("\r\n");
      out.write("				<script>\r\n");
      out.write("					alert(\"Lỗi hết hàng\");\r\n");
      out.write("					\r\n");
      out.write("				</script>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("				");
if(loiDanhGia != null && !loiDanhGia.isEmpty()){ 
					s.removeAttribute("Loidanhgia");
				
      out.write("\r\n");
      out.write("				<script>\r\n");
      out.write("					alert(\"Bạn chỉ được phép đánh giá khi mua sản phẩm của chúng tôi.\");\r\n");
      out.write("				</script>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				<div class=\"col-md-6 col-lg-7 p-b-30\">\r\n");
      out.write("					<div class=\"p-l-25 p-r-30 p-lr-0-lg\">\r\n");
      out.write("						<div class=\"wrap-slick3 flex-sb flex-w\">\r\n");
      out.write("							<div class=\"wrap-slick3-dots\"></div>\r\n");
      out.write("							<div class=\"wrap-slick3-arrows flex-sb-m flex-w\"></div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"slick3 gallery-lb\">\r\n");
      out.write("								");

								for (SanPham sp : listSP) {
									if (sp.getMaSanpham() == id) {
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<div class=\"item-slick3\" data-thumb=\"");
      out.print(sp.getDuongDanAnh());
      out.write("\">\r\n");
      out.write("									<div class=\"wrap-pic-w pos-relative\">\r\n");
      out.write("										<img src=\"");
      out.print(sp.getDuongDanAnh());
      out.write("\" alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("											class=\"flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04\"\r\n");
      out.write("											href=\"");
      out.print(sp.getDuongDanAnh());
      out.write("\"> <i class=\"fa fa-expand\"></i>\r\n");
      out.write("										</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6 col-lg-5 p-b-30\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"p-r-50 p-t-5 p-lr-0-lg\">\r\n");
      out.write("						<h4 class=\"mtext-105 cl2 js-name-detail p-b-14\">\r\n");
      out.write("							");
      out.print(sp.getTenSanPham());
      out.write("\r\n");
      out.write("						</h4>\r\n");
      out.write("\r\n");
      out.write("						<span class=\"mtext-106 cl2\"> ");
      out.print(sp.getGia());
      out.write("\r\n");
      out.write("						</span>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"stext-102 cl3 p-t-23\">\r\n");
      out.write("							");
      out.print(sp.getMoTa());
      out.write("\r\n");
      out.write("						</p>\r\n");
      out.write("						");

						}
						}
						
      out.write("\r\n");
      out.write("						<!--  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"p-t-33\">\r\n");
      out.write("							<form action=\"Giohangsanpham\" method=\"post\">\r\n");
      out.write("								<div class=\"flex-w flex-r-m p-b-10\">\r\n");
      out.write("									<div class=\"size-203 flex-c-m respon6\">Kích cỡ</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"size-204 respon6-next\">\r\n");
      out.write("										<div class=\"rs1-select2 bor8 bg0\">\r\n");
      out.write("											<select class=\"js-select2\" name=\"kichThuoc\">\r\n");
      out.write("												<option>Chọn kích cỡ</option>\r\n");
      out.write("												<option>S</option>\r\n");
      out.write("												<option>M</option>\r\n");
      out.write("												<option>L</option>\r\n");
      out.write("												<option>XL</option>\r\n");
      out.write("												<option>XXL</option>\r\n");
      out.write("											</select>\r\n");
      out.write("											<div class=\"dropDownSelect2\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"flex-w flex-r-m p-b-10\">\r\n");
      out.write("									<div class=\"size-203 flex-c-m respon6\">Màu sắc</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"size-204 respon6-next\">\r\n");
      out.write("										<div class=\"rs1-select2 bor8 bg0\">\r\n");
      out.write("											<select class=\"js-select2\" name=\"mauSac\">\r\n");
      out.write("												<option>Chọn màu sắc</option>\r\n");
      out.write("												");

												for (ChiTietSanPham c : listCTSP) {
													if (c.getMaSanPham() == id) {
												
      out.write("\r\n");
      out.write("												<option>");
      out.print(c.getMauSac());
      out.write("</option>\r\n");
      out.write("												");

												}
												}
												
      out.write("\r\n");
      out.write("											</select>\r\n");
      out.write("											<div class=\"dropDownSelect2\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"flex-w flex-r-m p-b-10\">\r\n");
      out.write("									<div class=\"size-204 flex-w flex-m respon6-next\">\r\n");
      out.write("										<div class=\"wrap-num-product flex-w m-r-20 m-tb-10\">\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m\">\r\n");
      out.write("												<i class=\"fs-16 zmdi zmdi-minus\"></i>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<input class=\"mtext-104 cl3 txt-center num-product\"\r\n");
      out.write("												type=\"number\" name=\"soLuong\" value=\"1\">\r\n");
      out.write("\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m\">\r\n");
      out.write("												<i class=\"fs-16 zmdi zmdi-plus\"></i>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<input type=\"hidden\" name=\"idSanPham\" value=\"");
      out.print(id);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("										<div class=\"button-group\" d-flex>\r\n");
      out.write("											<!-- Nút \"Thêm vào giỏ hàng\" với logo -->\r\n");
      out.write("											<button\r\n");
      out.write("												class=\"flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail \"\r\n");
      out.write("												name=\"gioHang\" value=\"gioHang\">\r\n");
      out.write("												<i class=\"zmdi zmdi-shopping-cart\"></i> Giỏ hàng\r\n");
      out.write("											</button>\r\n");
      out.write("\r\n");
      out.write("											<!-- Nút \"Đặt hàng\" với logo -->\r\n");
      out.write("\r\n");
      out.write("											<button\r\n");
      out.write("												class=\"flex-c-m stext-101 cl0 size-101 bg2 bor1 hov-btn2 p-lr-15 trans-04 js-order\"\r\n");
      out.write("												name=\"datHang\" value=\"datHang\">\r\n");
      out.write("												<i class=\"zmdi zmdi-check-circle\"></i> Đặt hàng\r\n");
      out.write("											</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!--  -->\r\n");
      out.write("					<div class=\"flex-w flex-m p-l-100 p-t-40 respon7\">\r\n");
      out.write("						<div class=\"flex-m bor9 p-r-10 m-r-11\">\r\n");
      out.write("							<a href=\"#\"\r\n");
      out.write("								class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 js-addwish-detail tooltip100\"\r\n");
      out.write("								data-tooltip=\"Add to Wishlist\"> <i\r\n");
      out.write("								class=\"zmdi zmdi-favorite\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<a href=\"#\"\r\n");
      out.write("							class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100\"\r\n");
      out.write("							data-tooltip=\"Facebook\"> <i class=\"fa fa-facebook\"></i>\r\n");
      out.write("						</a> <a href=\"#\"\r\n");
      out.write("							class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100\"\r\n");
      out.write("							data-tooltip=\"Twitter\"> <i class=\"fa fa-twitter\"></i>\r\n");
      out.write("						</a> <a href=\"#\"\r\n");
      out.write("							class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100\"\r\n");
      out.write("							data-tooltip=\"Google Plus\"> <i class=\"fa fa-google-plus\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"bor10 m-t-50 p-t-43 p-b-40\">\r\n");
      out.write("			<!-- Tab01 -->\r\n");
      out.write("			<div class=\"tab01\">\r\n");
      out.write("				<!-- Nav tabs -->\r\n");
      out.write("				<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("					<li class=\"nav-item p-b-10\"><a class=\"nav-link active\"\r\n");
      out.write("						data-toggle=\"tab\" href=\"#description\" role=\"tab\">Mô tả</a></li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"nav-item p-b-10\"><a class=\"nav-link\"\r\n");
      out.write("						data-toggle=\"tab\" href=\"#information\" role=\"tab\">Thông tin chi\r\n");
      out.write("							tiết </a></li>\r\n");
      out.write("							\r\n");
      out.write("							");

							Laydulieuchonguoidung lgnn = new Laydulieuchonguoidung();
							List<Danhgia> dh = lgnn.LayThongTinDanhGia();
							int soLuonDanhGia = 0;
							for(Danhgia danhGia : dh){
								if(danhGia.getMaSanPham()==id){
						soLuonDanhGia += 1;
								}}
							
      out.write("\r\n");
      out.write("					<li class=\"nav-item p-b-10\"><a class=\"nav-link\"\r\n");
      out.write("						data-toggle=\"tab\" href=\"#reviews\" role=\"tab\">Đánh giá (");
      out.print(soLuonDanhGia );
      out.write(")</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("				<!-- Tab panes -->\r\n");
      out.write("				<div class=\"tab-content p-t-43\">\r\n");
      out.write("					<!-- - -->\r\n");
      out.write("					<div class=\"tab-pane fade show active\" id=\"description\"\r\n");
      out.write("						role=\"tabpanel\">\r\n");
      out.write("						<div class=\"how-pos2 p-lr-15-md\">\r\n");
      out.write("							<p class=\"stext-102 cl6\">Thời trang năng động này được thiết\r\n");
      out.write("								kế dành cho những ai yêu thích phong cách thời trang trẻ trung\r\n");
      out.write("								và tiện lợi. Chất liệu nỉ cao cấp, mềm mại và thoáng khí mang\r\n");
      out.write("								đến cảm giác thoải mái suốt cả ngày, bất kể thời tiết se lạnh\r\n");
      out.write("								hay những buổi sáng sớm. Form dáng oversize hiện đại giúp bạn dễ\r\n");
      out.write("								dàng kết hợp với quần jeans, jogger hoặc chân váy, tạo nên phong\r\n");
      out.write("								cách cá tính mà không kém phần lịch sự. Đặc biệt, chiếc mũ rộng\r\n");
      out.write("								và túi trước tiện dụng là điểm nhấn hoàn hảo, vừa mang tính thẩm\r\n");
      out.write("								mỹ vừa đáp ứng nhu cầu thực tế. Với bảng màu đa dạng từ trung\r\n");
      out.write("								tính đến nổi bật, chiếc áo hoodie này chắc chắn sẽ là món đồ\r\n");
      out.write("								không thể thiếu trong tủ quần áo của bạn! .</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- - -->\r\n");
      out.write("					<div class=\"tab-pane fade\" id=\"information\" role=\"tabpanel\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-sm-10 col-md-8 col-lg-6 m-lr-auto\">\r\n");
      out.write("								<ul class=\"p-lr-28 p-lr-15-sm\">\r\n");
      out.write("									<li class=\"flex-w flex-t p-b-7\"><span\r\n");
      out.write("										class=\"stext-102 cl3 size-205\"> Cân nặng </span> <span\r\n");
      out.write("										class=\"stext-102 cl6 size-206\"> 0.79 kg </span></li>\r\n");
      out.write("\r\n");
      out.write("									<li class=\"flex-w flex-t p-b-7\"><span\r\n");
      out.write("										class=\"stext-102 cl3 size-205\"> Chiều cao </span> <span\r\n");
      out.write("										class=\"stext-102 cl6 size-206\"> 110 x 33 x 100 cm </span></li>\r\n");
      out.write("\r\n");
      out.write("									<li class=\"flex-w flex-t p-b-7\"><span\r\n");
      out.write("										class=\"stext-102 cl3 size-205\"> Chất liệu </span> <span\r\n");
      out.write("										class=\"stext-102 cl6 size-206\"> 60% cotton </span></li>\r\n");
      out.write("\r\n");
      out.write("									<li class=\"flex-w flex-t p-b-7\"><span\r\n");
      out.write("										class=\"stext-102 cl3 size-205\"> Màu sắc </span> <span\r\n");
      out.write("										class=\"stext-102 cl6 size-206\"> Black, Blue, Grey,\r\n");
      out.write("											Green, Red, White </span></li>\r\n");
      out.write("\r\n");
      out.write("									<li class=\"flex-w flex-t p-b-7\"><span\r\n");
      out.write("										class=\"stext-102 cl3 size-205\"> Kích cỡ </span> <span\r\n");
      out.write("										class=\"stext-102 cl6 size-206\">XXL, XL, L, M, S </span></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- - -->\r\n");
      out.write("					<div class=\"tab-pane fade\" id=\"reviews\" role=\"tabpanel\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-sm-10 col-md-8 col-lg-6 m-lr-auto\">\r\n");
      out.write("								<div class=\"p-b-30 m-lr-15-sm\">\r\n");
      out.write("									<!-- Review -->\r\n");
      out.write("									");

									
									for(Danhgia dhh : dh){
										if(dhh.getMaSanPham()==id){
											int i = 0;
									
      out.write("\r\n");
      out.write("									<div class=\"flex-w flex-t p-b-68\">\r\n");
      out.write("										<div class=\"wrap-pic-s size-109 bor0 of-hidden m-r-18 m-t-6\">\r\n");
      out.write("											<img src=\"images/meoconcute.jpg\" alt=\"AVATAR\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"size-207\">\r\n");
      out.write("										<span class=\"mtext-107 cl2 p-r-20\"> ");
      out.print(dhh.getNgayDang() );
      out.write(" </span>\r\n");
      out.write("											<div class=\"d-flex justify-content-between align-items-center p-b-17 \">\r\n");
      out.write("												<span class=\"mtext-107 cl2 p-r-20\"> ");
      out.print(dhh.getTenNguoiDung() );
      out.write(" </span>\r\n");
      out.write("												 <span\r\n");
      out.write("													class=\"fs-18 cl11\">\r\n");
      out.write("													");

													while(i < dhh.getSoSao()){ 
													
      out.write("\r\n");
      out.write("													 <i class=\"zmdi zmdi-star\"></i> \r\n");
      out.write("													 ");

													 i = i+1;} 
													 
      out.write("\r\n");
      out.write("												</span>\r\n");
      out.write("											</div>\r\n");
      out.write("											\r\n");
      out.write("											<p class=\"stext-102 cl6\">");
      out.print(dhh.getNoiDung() );
      out.write("</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<!-- Phản hồi của quản trị viên -->\r\n");
      out.write("									 ");

									 if(dhh.getNoiDungPhanHoi() != null && dhh.getMaNguoiDung()==user.get(0).getMaTaiKhoan()){
									 
      out.write("\r\n");
      out.write("										<div class=\"admin-response mt-4\">\r\n");
      out.write("											<h5 class=\"cl2\">\r\n");
      out.write("												Admin phản hồi\r\n");
      out.write("												");
      out.print(dhh.getTenNguoiDung());
      out.write("</h5>\r\n");
      out.write("											<div class=\"d-flex align-items-center\">\r\n");
      out.write("												<!-- Hình ảnh của quản trị viên -->\r\n");
      out.write("												<div class=\"wrap-pic-s size-109 bor0 of-hidden m-r-18 m-t-6\">\r\n");
      out.write("													<img src=\"images/admin-avatar.jpg\" alt=\"Admin Avatar\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<!-- Nội dung phản hồi -->\r\n");
      out.write("												<p class=\"stext-102 cl6\">\r\n");
      out.write("													");
      out.print(dhh.getNoiDungPhanHoi());
      out.write("\r\n");
      out.write("												</p>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										");

										}
										
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									");

									}
									}
									
      out.write("\r\n");
      out.write("									<!-- Add review -->\r\n");
      out.write("									<form class=\"w-full\" action=\"Danhgiasanpham\">\r\n");
      out.write("										<h5 class=\"mtext-108 cl2 p-b-7\">Thêm đánh giá</h5>\r\n");
      out.write("										<input value=\"");
      out.print(id);
      out.write("\" name=\"idSanPham\" type=\"hidden\">\r\n");
      out.write("										<p class=\"stext-102 cl6\">Vui lòng hãy đánh giá sản phẩm này một cách khách quan nhất*</p>\r\n");
      out.write("\r\n");
      out.write("										<select name=\"soSao\" id=\"number\">\r\n");
      out.write("										<option value=\"0\" class=\"star-option\"><span\r\n");
      out.write("													class=\"star\">★</span>\r\n");
      out.write("											</option>\r\n");
      out.write("											<option value=\"1\" class=\"star-option\"><span\r\n");
      out.write("													class=\"star\">★</span>1\r\n");
      out.write("											</option>\r\n");
      out.write("											<option value=\"2\" class=\"star-option\"><span\r\n");
      out.write("													class=\"star\">★</span>2\r\n");
      out.write("											</option>\r\n");
      out.write("											<option value=\"3\" class=\"star-option\"><span\r\n");
      out.write("													class=\"star\">★</span>3\r\n");
      out.write("											</option>\r\n");
      out.write("											<option value=\"4\" class=\"star-option\"><span\r\n");
      out.write("													class=\"star\">★</span>4\r\n");
      out.write("											</option>\r\n");
      out.write("											<option value=\"5\" class=\"star-option\"><span\r\n");
      out.write("													class=\"star\">★</span>5\r\n");
      out.write("											</option>\r\n");
      out.write("										</select>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"row p-b-25\">\r\n");
      out.write("											<div class=\"col-12 p-b-5\">\r\n");
      out.write("												<label class=\"stext-102 cl3\" for=\"review\">Nội dung</label>\r\n");
      out.write("												<textarea\r\n");
      out.write("													class=\"size-110 bor8 stext-102 cl2 p-lr-20 p-tb-10\"\r\n");
      out.write("													id=\"review\" name=\"noiDungDanhGia\"></textarea>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<button\r\n");
      out.write("											class=\"flex-c-m stext-101 cl0 size-112 bg7 bor11 hov-btn3 p-lr-15 trans-04 m-b-10\">\r\n");
      out.write("											Đánh giá</button>\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"bg6 flex-c-m flex-w size-302 m-t-73 p-tb-15\">\r\n");
      out.write("			<span class=\"stext-107 cl6 p-lr-25\"> Phong cách </span> <span\r\n");
      out.write("				class=\"stext-107 cl6 p-lr-25\"> Đột phá </span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Related Products -->\r\n");
      out.write("	<section class=\"sec-relate-product bg0 p-t-45 p-b-105\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"p-b-45\">\r\n");
      out.write("				<h3 class=\"ltext-106 cl5 txt-center\">Sản phẩm tương tự</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Slide2 -->\r\n");
      out.write("			<div class=\"wrap-slick2\">\r\n");
      out.write("				<div class=\"slick2\">\r\n");
      out.write("					");

					for (SanPham sp : listSP) {
						if (sp.getMaSanpham() != id) {
					
      out.write("\r\n");
      out.write("					<div class=\"item-slick2 p-l-15 p-r-15 p-t-15 p-b-15\">\r\n");
      out.write("						<!-- Block2 -->\r\n");
      out.write("						<div class=\"block2\">\r\n");
      out.write("							<div class=\"block2-pic hov-img0\">\r\n");
      out.write("								<img src=\"");
      out.print(sp.getDuongDanAnh());
      out.write("\" alt=\"IMG-PRODUCT\"\r\n");
      out.write("									style=\"height: 300px;\"> <a\r\n");
      out.write("									href=\"Giohangproducttail?id=");
      out.print(sp.getMaSanpham());
      out.write("\"\r\n");
      out.write("									class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 \">\r\n");
      out.write("									Xem nhanh </a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
      out.write("								<div class=\"block2-txt-child1 flex-col-l \">\r\n");
      out.write("									<a href=\"Giohangproducttail?id=");
      out.print(sp.getMaSanpham());
      out.write("\"\r\n");
      out.write("										class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\"> ");
      out.print(sp.getTenSanPham());
      out.write("\r\n");
      out.write("									</a> <span class=\"stext-105 cl3\"> $");
      out.print(sp.getGia());
      out.write("\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
      out.write("									<a href=\"#\"\r\n");
      out.write("										class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
      out.write("										<img class=\"icon-heart1 dis-block trans-04\"\r\n");
      out.write("										src=\"images/icons/icon-heart-01.png\" alt=\"ICON\"> <img\r\n");
      out.write("										class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
      out.write("										src=\"images/icons/icon-heart-02.png\" alt=\"ICON\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

					}
					}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<footer class=\"bg3 p-t-75 p-b-32\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">Categories</h4>\r\n");
      out.write("\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Women </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Men </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Shoes </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Watches </a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">Help</h4>\r\n");
      out.write("\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Track Order </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Returns </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Shipping </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> FAQs </a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">GET IN TOUCH</h4>\r\n");
      out.write("\r\n");
      out.write("					<p class=\"stext-107 cl7 size-201\">Any questions? Let us know in\r\n");
      out.write("						store at 8th floor, 379 Hudson St, New York, NY 10018 or call us\r\n");
      out.write("						on (+1) 96 716 6879</p>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"p-t-27\">\r\n");
      out.write("						<a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\"> <i\r\n");
      out.write("							class=\"fa fa-facebook\"></i>\r\n");
      out.write("						</a> <a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\"> <i\r\n");
      out.write("							class=\"fa fa-instagram\"></i>\r\n");
      out.write("						</a> <a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\"> <i\r\n");
      out.write("							class=\"fa fa-pinterest-p\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">Newsletter</h4>\r\n");
      out.write("\r\n");
      out.write("					<form>\r\n");
      out.write("						<div class=\"wrap-input1 w-full p-b-4\">\r\n");
      out.write("							<input class=\"input1 bg-none plh1 stext-107 cl7\" type=\"text\"\r\n");
      out.write("								name=\"email\" placeholder=\"email@example.com\">\r\n");
      out.write("							<div class=\"focus-input1 trans-04\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"p-t-18\">\r\n");
      out.write("							<button\r\n");
      out.write("								class=\"flex-c-m stext-101 cl0 size-103 bg1 bor1 hov-btn2 p-lr-15 trans-04\">\r\n");
      out.write("								Subscribe</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"p-t-40\">\r\n");
      out.write("				<div class=\"flex-c-m flex-w p-b-18\">\r\n");
      out.write("					<a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-01.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-02.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-03.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-04.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-05.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<p class=\"stext-107 cl6 txt-center\">\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					Copyright &copy;\r\n");
      out.write("					<script>\r\n");
      out.write("						document.write(new Date().getFullYear());\r\n");
      out.write("					</script>\r\n");
      out.write("					All rights reserved | Made with <i class=\"fa fa-heart-o\"\r\n");
      out.write("						aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\"\r\n");
      out.write("						target=\"_blank\">Colorlib</a> &amp; distributed by <a\r\n");
      out.write("						href=\"https://themewagon.com\" target=\"_blank\">ThemeWagon</a>\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Back to top -->\r\n");
      out.write("	<div class=\"btn-back-to-top\" id=\"myBtn\">\r\n");
      out.write("		<span class=\"symbol-btn-back-to-top\"> <i\r\n");
      out.write("			class=\"zmdi zmdi-chevron-up\"></i>\r\n");
      out.write("		</span>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/animsition/js/animsition.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/bootstrap/js/popper.js\"></script>\r\n");
      out.write("	<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/select2/select2.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\".js-select2\").each(function() {\r\n");
      out.write("			$(this).select2({\r\n");
      out.write("				minimumResultsForSearch : 20,\r\n");
      out.write("				dropdownParent : $(this).next('.dropDownSelect2')\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/daterangepicker/moment.min.js\"></script>\r\n");
      out.write("	<script src=\"vendor/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/slick/slick.min.js\"></script>\r\n");
      out.write("	<script src=\"js/slick-custom.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/parallax100/parallax100.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.parallax100').parallax100();\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/MagnificPopup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.gallery-lb').each(function() { // the containers for all your galleries\r\n");
      out.write("			$(this).magnificPopup({\r\n");
      out.write("				delegate : 'a', // the selector for gallery item\r\n");
      out.write("				type : 'image',\r\n");
      out.write("				gallery : {\r\n");
      out.write("					enabled : true\r\n");
      out.write("				},\r\n");
      out.write("				mainClass : 'mfp-fade'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/isotope/isotope.pkgd.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/sweetalert/sweetalert.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.js-addwish-b2, .js-addwish-detail').on('click', function(e) {\r\n");
      out.write("			e.preventDefault();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$('.js-addwish-b2').each(\r\n");
      out.write("				function() {\r\n");
      out.write("					var nameProduct = $(this).parent().parent().find(\r\n");
      out.write("							'.js-name-b2').html();\r\n");
      out.write("					$(this).on('click', function() {\r\n");
      out.write("						swal(nameProduct, \"is added to wishlist !\", \"success\");\r\n");
      out.write("\r\n");
      out.write("						$(this).addClass('js-addedwish-b2');\r\n");
      out.write("						$(this).off('click');\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("		$('.js-addwish-detail').each(\r\n");
      out.write("				function() {\r\n");
      out.write("					var nameProduct = $(this).parent().parent().parent().find(\r\n");
      out.write("							'.js-name-detail').html();\r\n");
      out.write("\r\n");
      out.write("					$(this).on('click', function() {\r\n");
      out.write("						swal(nameProduct, \"is added to wishlist !\", \"success\");\r\n");
      out.write("\r\n");
      out.write("						$(this).addClass('js-addedwish-detail');\r\n");
      out.write("						$(this).off('click');\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("		/*---------------------------------------------*/\r\n");
      out.write("\r\n");
      out.write("		$('.js-addcart-detail').each(\r\n");
      out.write("				function() {\r\n");
      out.write("					var nameProduct = $(this).parent().parent().parent()\r\n");
      out.write("							.parent().find('.js-name-detail').html();\r\n");
      out.write("					$(this).on(\r\n");
      out.write("							'click',\r\n");
      out.write("							function() {\r\n");
      out.write("								swal(nameProduct,\r\n");
      out.write("										\"Thêm vào giỏ hàng thành công !\",\r\n");
      out.write("										\"success\");\r\n");
      out.write("							});\r\n");
      out.write("				});\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/perfect-scrollbar/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.js-pscroll').each(function() {\r\n");
      out.write("			$(this).css('position', 'relative');\r\n");
      out.write("			$(this).css('overflow', 'hidden');\r\n");
      out.write("			var ps = new PerfectScrollbar(this, {\r\n");
      out.write("				wheelSpeed : 1,\r\n");
      out.write("				scrollingThreshold : 1000,\r\n");
      out.write("				wheelPropagation : false,\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(window).on('resize', function() {\r\n");
      out.write("				ps.update();\r\n");
      out.write("			})\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
