/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2024-12-23 08:48:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.User;
import model.BaiViet;
import java.util.List;
import Reponsitory.LaydulieuReponsitory;

public final class Quanlibaiviet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("model.BaiViet");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("Reponsitory.LaydulieuReponsitory");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("<title>Admin/Category</title>\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link href=\"assetsquantri/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("<link href=\"assetsquantri/img/apple-touch-icon.png\"\r\n");
      out.write("	rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins...700,700i\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS Files -->\r\n");
      out.write("<link href=\"assetsquantri/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/bootstrap-icons/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/boxicons/css/boxicons.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/quill/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/quill/quill.bubble.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/remixicon/remixicon.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assetsquantri/vendor/simple-datatables/style.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Template Main CSS File -->\r\n");
      out.write("<link href=\"assetsquantri/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("<!-- =======================================================\r\n");
      out.write("  * Template Name: NiceAdmin\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/\r\n");
      out.write("  * Updated: Apr 20 2024 with Bootstrap v5.3.3\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	/* font-family: Arial, sans-serif; */\r\n");
      out.write("	/* background-color: #FFFFFF; /* Màu nền trắng */\r\n");
      out.write("	color: #FFFFFF; /* Màu chữ trắng */ */\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin: 20px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container {\r\n");
      out.write("	background-color: #f9f9f9;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container input, .form-container textarea, .form-container button\r\n");
      out.write("	{\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 12px;\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	border: 2px solid #ddd;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container input:focus, .form-container textarea:focus {\r\n");
      out.write("	border-color: #4CAF50; /* Viền xanh khi focus */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container textarea {\r\n");
      out.write("	height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-actions {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write(".form-actions button {\r\n");
      out.write("	width: 48%;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	padding: 12px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	border: 2px solid #4CAF50;\r\n");
      out.write("	background-color: #4CAF50;\r\n");
      out.write("	color: white;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-actions button:hover {\r\n");
      out.write("	background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nút Đóng */\r\n");
      out.write(".form-actions button.delete {\r\n");
      out.write("	background-color: #f44336;\r\n");
      out.write("	border-color: #f44336;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-actions button.delete:hover {\r\n");
      out.write("	background-color: #e53935;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar input {\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	border: 2px solid #ddd;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin: 20px 0;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("	padding: 12px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mau {\r\n");
      out.write("	background-color: #4CAF50;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write(".mauduoi {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    color: #888;  /* Màu chữ nhạt */\r\n");
      out.write("    font-family: 'Arial', sans-serif;  /* Kiểu chữ thanh thoát */\r\n");
      out.write("    font-size: 16px;  /* Kích thước chữ hợp lý */\r\n");
      out.write("    line-height: 1.5;  /* Giãn cách dòng để văn bản dễ đọc hơn */\r\n");
      out.write("    letter-spacing: 0.5px;  /* Tăng khoảng cách giữa các ký tự */\r\n");
      out.write("    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1); /* Thêm bóng nhẹ cho chữ */\r\n");
      out.write("    padding: 10px;  /* Tăng khoảng cách bên trong để văn bản không sát viền */\r\n");
      out.write("    border-radius: 8px;  /* Bo góc cho phần tử */\r\n");
      out.write("    transition: color 0.3s ease, background-color 0.3s ease;  /* Hiệu ứng chuyển màu mượt mà */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mauduoi:hover {\r\n");
      out.write("    color: #4CAF50;  /* Đổi màu chữ khi hover */\r\n");
      out.write("    background-color: #f1f1f1;  /* Đổi màu nền khi hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("tr:nth-child(even) {\r\n");
      out.write("	background-color: #f2f2f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nút Sửa và Xóa đẹp hơn */\r\n");
      out.write(".action-btn {\r\n");
      out.write("	padding: 8px 15px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.3s ease;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-btn {\r\n");
      out.write("	background-color: #4CAF50;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-btn:hover {\r\n");
      out.write("	background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-btn {\r\n");
      out.write("	background-color: #f44336;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-btn:hover {\r\n");
      out.write("	background-color: #e53935;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.add {\r\n");
      out.write("	background-color: #87CEFA;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.add:hover {\r\n");
      out.write("	background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Media Queries for responsive design */\r\n");
      out.write("@media ( max-width : 768px) {\r\n");
      out.write("	.container {\r\n");
      out.write("		width: 90%;\r\n");
      out.write("	}\r\n");
      out.write("	.form-container {\r\n");
      out.write("		padding: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	.form-container input, .form-container textarea, .form-container button\r\n");
      out.write("		{\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	.search-bar input {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	table {\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("	}\r\n");
      out.write("	.form-actions {\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("	}\r\n");
      out.write("	.form-actions button {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 480px) {\r\n");
      out.write("	h1 {\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	.search-bar input {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	table {\r\n");
      out.write("		font-size: 12px;\r\n");
      out.write("	}\r\n");
      out.write("	.form-container input, .form-container textarea {\r\n");
      out.write("		font-size: 12px;\r\n");
      out.write("		padding: 8px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- ======= Header ======= -->\r\n");
      out.write("	");

	String projectName = request.getContextPath(); // Lấy tên dự án
	HttpSession s = request.getSession(false);
	List<User> listt = (List<User>) session.getAttribute("Ghinhotaikhoan");
	if(listt == null){
	
      out.write("\r\n");
      out.write("	 <script >\r\n");
      out.write("                alert(\"Vui lòng đăng nhập để xem thông tin\"); // Hiển thị thông báo\r\n");
      out.write("                window.location.href = \"login.jsp\";\r\n");
      out.write("              </script>\r\n");
      out.write("	\r\n");
      out.write("	");
} else{
	for(User u : listt){
		if(u.getMaQuyen()==3){
	
	
      out.write("\r\n");
      out.write("	 <script >\r\n");
      out.write("                alert(\"Bạn không phải là admin vui lòng truy cập tài khoản admin.\"); // Hiển thị thông báo\r\n");
      out.write("                window.location.href = \"login.jsp\";\r\n");
      out.write("              </script>\r\n");
      out.write("	");
}}} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ======= Header ======= -->\r\n");
      out.write("	<header id=\"header\" class=\"header fixed-top d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("			<a href=\"index.html\" class=\"logo d-flex align-items-center\"> <img\r\n");
      out.write("				src=\"assetsquantri/img/logo.png\" alt=\"\"> <span\r\n");
      out.write("				class=\"d-none d-lg-block\">T3admin</span>\r\n");
      out.write("			</a> <i class=\"bi bi-list toggle-sidebar-btn\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Logo -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"header-nav ms-auto\">\r\n");
      out.write("			<ul class=\"d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown pe-3\">\r\n");
      out.write("					\r\n");
      out.write("			<a class=\"nav-link nav-profile d-flex align-items-center pe-0\"\r\n");
      out.write("					href=\"#\" data-bs-toggle=\"dropdown\"> <i\r\n");
      out.write("						class=\"bi bi-person-circle\"></i> <span\r\n");
      out.write("						");
if(listt != null){
						for(User u : listt) {
      out.write("\r\n");
      out.write("						class=\"d-none d-md-block dropdown-toggle ps-2\">");
      out.print(u.getHoTen());
      out.write("\r\n");
      out.write("							</span>\r\n");
      out.write("				</a> <!-- End Profile Image Icon -->\r\n");
      out.write("\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">\r\n");
      out.write("						<li class=\"dropdown-header\">\r\n");
      out.write("							<h6>");
      out.print(u.getTenTaiKhoan());
      out.write("</h6>\r\n");
      out.write("							");
if(u.getMaQuyen() == 1) {
      out.write("\r\n");
      out.write("							<span>Quản trị viên</span>\r\n");
      out.write("							");
} else{
      out.write("\r\n");
      out.write("							<span>Khách hàng</span>\r\n");
      out.write("							");
} 
      out.write("\r\n");
      out.write("						</li>\r\n");
      out.write("						\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("							<li><a class=\"dropdown-item d-flex align-items-center\"\r\n");
      out.write("							href=\"Thongtincanhan.jsp\"> <i class=\"bi bi-person\"></i> <span>Thông tin cá nhân\r\n");
      out.write("									</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item d-flex align-items-center\"\r\n");
      out.write("							href=\"Dangxuat\"> <i class=\"bi bi-box-arrow-right\"></i> <span>Đăng\r\n");
      out.write("									xuất</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul> <!-- End Profile Dropdown Items -->\r\n");
      out.write("				</li>\r\n");
      out.write("				");
} }
      out.write("\r\n");
      out.write("				<!-- End Profile Nav -->\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- End Icons Navigation -->\r\n");
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ======= Sidebar ======= -->\r\n");
      out.write("	<aside id=\"sidebar\" class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("		<ul class=\"sidebar-nav\" id=\"sidebar-nav\">\r\n");
      out.write("		<li class=\"nav-heading\">Tổng quan dữ liệu</li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/Bieudodoanhthu\"> <i class=\"fas fa-tachometer-alt\"></i> <span>Biểu đồ\r\n");
      out.write("						thống kê</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("\r\n");
      out.write("			<li class=\"nav-heading\">Quản lý bán hàng</li>\r\n");
      out.write("<li class=\"nav-item\"><a class=\"nav-link collapsed\"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/category.jsp\"> <i\r\n");
      out.write("					class=\"bi bi-layout-text-window-reverse\"></i> <span>Danh mục</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"");
      out.print(projectName);
      out.write("/Donhangquantri.jsp\">\r\n");
      out.write("					<i class=\"bi bi-cart\"></i> <span>Đơn hàng</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/productquantri.jsp\"> <i\r\n");
      out.write("					class=\"bi bi-grid\"></i> <span>Sản phẩm</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/Quanlidanhgia.jsp\"> <i\r\n");
      out.write("					class=\"fa fa-star\"></i> <span>Đánh giá</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/Quantrikhuyenmai.jsp\"> <i\r\n");
      out.write("					class=\"fas fa-gift\"></i> <span>Khuyến mãi</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link \"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/Quanlibaiviet.jsp\"> <i\r\n");
      out.write("					class=\"fa fa-newspaper\"></i> <span>Bài viết</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-heading\">Quản lý tài khoản</li>\r\n");
      out.write("\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/account.jsp\"> <i class=\"bi bi-person\"></i>\r\n");
      out.write("					<span>Tài khoản</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<!-- End Profile Page Nav -->\r\n");
      out.write("\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\"\r\n");
      out.write("				href=\"");
      out.print(projectName);
      out.write("/group.jsp\"> <i\r\n");
      out.write("					class=\"bi bi-question-circle\"></i> <span>Phân quyền</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<!-- End F.A.Q Page Nav -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("	</aside>\r\n");
      out.write("	<!-- End Sidebar-->\r\n");
      out.write("\r\n");
      out.write("	<main id=\"main\" class=\"main\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"pagetitle\">\r\n");
      out.write("			<h1>Bài viết</h1>\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ol class=\"breadcrumb\">\r\n");
      out.write("					<li class=\"breadcrumb-item\"><a href=\"index.html\">Quản lý bán hàng</a></li>\r\n");
      out.write("					<li class=\"breadcrumb-item active\">Bài viết</li>\r\n");
      out.write("				</ol>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Page Title -->\r\n");
      out.write("\r\n");
      out.write("		<section class=\"section\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<div class=\"card-body\" style=\"padding-top: 30px;\">\r\n");
      out.write("			<!-- Form Thêm / Sửa Bài Viết -->\r\n");
      out.write("			<div id=\"formContainer\" class=\"form-container\" style=\"display: none;\">\r\n");
      out.write("				<h2 id=\"formTitle\">Thêm Bài Viết</h2>\r\n");
      out.write("				<form id=\"articleForm\" action=\"Thembaiviet\" method=\"post\">\r\n");
      out.write("					\r\n");
      out.write("					<input type=\"text\" id=\"title\" name=\"tenBai\" placeholder=\"Tên Bài\"\r\n");
      out.write("						required><br>\r\n");
      out.write("					<textarea id=\"content\" name=\"noiDung\" placeholder=\"Nội Dung\"\r\n");
      out.write("						required></textarea>\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-actions\">\r\n");
      out.write("						<button type=\"submit\" class=\"add\" onclick=\"saveArticle()\">Lưu</button>\r\n");
      out.write("						<button type=\"button\" class=\"delete\" onclick=\"closeForm()\">Đóng</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Thanh Tìm Kiếm -->\r\n");
      out.write("			<div class=\"search-bar\">\r\n");
      out.write("				<input type=\"text\" id=\"searchInput\"\r\n");
      out.write("					placeholder=\"Tìm kiếm theo tên hoặc nội dung...\"\r\n");
      out.write("					onkeyup=\"searchArticles()\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<button class=\"add\" onclick=\"showForm('add')\" style=\"border-radius: 10px\">Thêm Bài Viết</button>\r\n");
      out.write("\r\n");
      out.write("			<table id=\"articlesTable\">\r\n");
      out.write("<thead class=\"mau\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>Mã Bài</th>\r\n");
      out.write("						<th>Mã Quản Trị</th>\r\n");
      out.write("						<th>Tên Bài</th>\r\n");
      out.write("						<th>Nội Dung</th>\r\n");
      out.write("						<th>Thời Gian</th>\r\n");
      out.write("						<th>Hành Động</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				\r\n");
      out.write("				<tbody class=\"mauduoi\">\r\n");
      out.write("				");

				LaydulieuReponsitory lg = new LaydulieuReponsitory();
				List<BaiViet> b = lg.LayThongTinBaiViet();
				for(BaiViet baiViet : b){
				
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>");
      out.print(baiViet.getMaBaiViet() );
      out.write("</th>\r\n");
      out.write("						<th>");
      out.print(baiViet.getMaNguoiDung() );
      out.write("</th>\r\n");
      out.write("						<th>");
      out.print(baiViet.getTenBai() );
      out.write("</th>\r\n");
      out.write("						<th>");
      out.print(baiViet.getNoiDung() );
      out.write("</th>\r\n");
      out.write("						<th>");
      out.print(baiViet.getThoiGian() );
      out.write("</th>\r\n");
      out.write("						<th>\r\n");
      out.write("						<form action=\"Xoabaiviet\" method=\"post\">\r\n");
      out.write("						<input type=\"hidden\" name=\"xoaBaiViet\" value=\"");
      out.print(baiViet.getMaBaiViet());
      out.write("\">\r\n");
      out.write("						<button class=\"action-btn delete-btn\" onclick=\"thongbao()\">Xóa</button>\r\n");
      out.write("						</form>\r\n");
      out.write("						</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	</main>\r\n");
      out.write("	<!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ======= Footer ======= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<a href=\"#\"\r\n");
      out.write("		class=\"back-to-top d-flex align-items-center justify-content-center\"><i\r\n");
      out.write("		class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\r\n");
      out.write("	<!-- Vendor JS Files -->\r\n");
      out.write("	<script src=\"assetsquantri/vendor/apexcharts/apexcharts.min.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/chart.js/chart.umd.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/echarts/echarts.min.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/quill/quill.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"assetsquantri/vendor/simple-datatables/simple-datatables.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/tinymce/tinymce.min.js\"></script>\r\n");
      out.write("	<script src=\"assetsquantri/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Template Main JS File -->\r\n");
      out.write("	<script src=\"assetsquantri/js/main.js\"></script>\r\n");
      out.write("	<script> \r\n");
      out.write("	document.getElementById('addb').addEventListener('click', () => {toggleUpload();});\r\n");
      out.write("	function toggleUpload() {\r\n");
      out.write("    const addForm = document.getElementById('addf');\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    if (addForm.classList.contains('hide')) {\r\n");
      out.write("        addForm.classList.remove('hide');\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    } else {\r\n");
      out.write("        addForm.classList.add('hide');\r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("	let articles = [\r\n");
      out.write("        { articleId: 1, adminId: 'A001', title: 'Bài viết 1', content: 'Nội dung bài viết 1', time: '2024-12-20T10:00' },\r\n");
      out.write("        { articleId: 2, adminId: 'A002', title: 'Bài viết 2', content: 'Nội dung bài viết 2', time: '2024-12-21T11:00' }\r\n");
      out.write("    ];\r\n");
      out.write("\r\n");
      out.write("    function showForm(mode, article = null) {\r\n");
      out.write("        document.getElementById('formContainer').style.display = 'block';\r\n");
      out.write("        if (mode === 'add') {\r\n");
      out.write("            document.getElementById('formTitle').textContent = 'Thêm Bài Viết';\r\n");
      out.write("            document.getElementById('articleForm').reset();\r\n");
      out.write("        } else if (mode === 'edit' && article) {\r\n");
      out.write("            document.getElementById('formTitle').textContent = 'Sửa Bài Viết';\r\n");
      out.write("            document.getElementById('articleId').value = article.articleId;\r\n");
      out.write("document.getElementById('adminId').value = article.adminId;\r\n");
      out.write("            document.getElementById('title').value = article.title;\r\n");
      out.write("            document.getElementById('content').value = article.content;\r\n");
      out.write("            document.getElementById('time').value = article.time;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function closeForm() {\r\n");
      out.write("        document.getElementById('formContainer').style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function saveArticle() {\r\n");
      out.write("        let articleId = document.getElementById('articleId').value;\r\n");
      out.write("        let adminId = document.getElementById('adminId').value;\r\n");
      out.write("        let title = document.getElementById('title').value;\r\n");
      out.write("        let content = document.getElementById('content').value;\r\n");
      out.write("        let time = document.getElementById('time').value;\r\n");
      out.write("\r\n");
      out.write("        if (!articleId || !adminId || !title || !content || !time) {\r\n");
      out.write("            alert('Vui lòng điền đầy đủ thông tin!');\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        let article = { articleId, adminId, title, content, time };\r\n");
      out.write("        \r\n");
      out.write("        // Check if it's a new article or an edit\r\n");
      out.write("        if (articles.some(a => a.articleId == articleId)) {\r\n");
      out.write("            // Update article\r\n");
      out.write("            articles = articles.map(a => a.articleId == articleId ? article : a);\r\n");
      out.write("        } else {\r\n");
      out.write("            // Add new article\r\n");
      out.write("            articles.push(article);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        closeForm();\r\n");
      out.write("        renderTable();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function renderTable() {\r\n");
      out.write("        let tableBody = document.getElementById('articlesTable').getElementsByTagName('tbody')[0];\r\n");
      out.write("        tableBody.innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("        articles.forEach(article => {\r\n");
      out.write("            let row = document.createElement('tr');\r\n");
      out.write("            row.innerHTML = `\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.articleId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.adminId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.content}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.time}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <button class=\"action-btn edit-btn\" onclick=\"showForm('edit', ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${JSON.stringify(article)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">Sửa</button>\r\n");
      out.write("                    <button class=\"action-btn delete-btn\" onclick=\"deleteArticle(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.articleId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">Xóa</button>\r\n");
      out.write("                </td>\r\n");
      out.write("            `;\r\n");
      out.write("            tableBody.appendChild(row);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function deleteArticle(articleId) {\r\n");
      out.write("        if (confirm('Bạn có chắc muốn xóa bài viết này?')) {\r\n");
      out.write("            articles = articles.filter(article => article.articleId != articleId);\r\n");
      out.write("            renderTable();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function searchArticles() {\r\n");
      out.write("        let searchTerm = document.getElementById('searchInput').value.toLowerCase();\r\n");
      out.write("        let filteredArticles = articles.filter(article =>\r\n");
      out.write("            article.title.toLowerCase().includes(searchTerm) || \r\n");
      out.write("            article.content.toLowerCase().includes(searchTerm)\r\n");
      out.write("        );\r\n");
      out.write("        renderFilteredTable(filteredArticles);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function renderFilteredTable(filteredArticles) {\r\n");
      out.write("        let tableBody = document.getElementById('articlesTable').getElementsByTagName('tbody')[0];\r\n");
      out.write("tableBody.innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("        filteredArticles.forEach(article => {\r\n");
      out.write("            let row = document.createElement('tr');\r\n");
      out.write("            row.innerHTML = `\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.articleId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.adminId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.content}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.time}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <button class=\"action-btn edit-btn\" onclick=\"showForm('edit', ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${JSON.stringify(article)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">Sửa</button>\r\n");
      out.write("                    <button class=\"action-btn delete-btn\" onclick=\"deleteArticle(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.articleId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">Xóa</button>\r\n");
      out.write("                </td>\r\n");
      out.write("            `;\r\n");
      out.write("            tableBody.appendChild(row);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    function thongbao() {\r\n");
      out.write("    	alert('Bạn chắc chắn muốn xóa chứ huhu!');\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    // Render the table on page load\r\n");
      out.write("    renderTable();\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
