/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2024-12-23 04:40:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.User;
import Reponsitory.Laydulieuchonguoidung;
import model.GioHang;
import model.ChiTietSanPham;
import model.SanPham;
import java.util.List;
import Reponsitory.LaydulieuReponsitory;

public final class shopping_002dcard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("model.GioHang");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.ChiTietSanPham");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("Reponsitory.LaydulieuReponsitory");
    _jspx_imports_classes.add("Reponsitory.Laydulieuchonguoidung");
    _jspx_imports_classes.add("model.SanPham");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Giỏ hàng</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"assetsquantri/img/logo.png\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"fonts/iconic/css/material-design-iconic-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"fonts/linearicons-v1.0.0/icon-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animate/animate.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/select2/select2.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/slick/slick.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/MagnificPopup/magnific-popup.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"vendor/perfect-scrollbar/perfect-scrollbar.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/util.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<style>\r\n");
      out.write("/* Reset các kiểu mặc định */\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	background-color: #f5f5f5;\r\n");
      out.write("	color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-container {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	margin: 50px auto;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	overflow: auto;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-item {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	border-bottom: 1px solid #eee;\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-image {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-info {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	padding: 0 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-name {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-price {\r\n");
      out.write("	color: #f56c6c;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-color {\r\n");
      out.write("	color: #888;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".quantity-control {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".quantity {\r\n");
      out.write("	width: 50px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-minus, .btn-plus {\r\n");
      out.write("	background-color: #eee;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	padding: 5px 10px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-minus:hover, .btn-plus:hover {\r\n");
      out.write("	background-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-remove {\r\n");
      out.write("	background-color: #ff4d4d;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 8px 15px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-remove:hover {\r\n");
      out.write("	background-color: #e60000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-total {\r\n");
      out.write("	text-align: right;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-checkout {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 12px;\r\n");
      out.write("	background-color: #28a745;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-checkout:hover {\r\n");
      out.write("	background-color: #218838;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Media Queries cho Responsive */\r\n");
      out.write("@media ( max-width : 768px) {\r\n");
      out.write("	.cart-container {\r\n");
      out.write("		width: 95%;\r\n");
      out.write("		margin: 20px auto;\r\n");
      out.write("		padding: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	.cart-item {\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		align-items: flex-start;\r\n");
      out.write("	}\r\n");
      out.write("	.product-image {\r\n");
      out.write("		width: 80px;\r\n");
      out.write("		height: 80px;\r\n");
      out.write("	}\r\n");
      out.write("	.product-info {\r\n");
      out.write("		padding: 0 10px;\r\n");
      out.write("	}\r\n");
      out.write("	.quantity-control {\r\n");
      out.write("		gap: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.btn-remove {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 480px) {\r\n");
      out.write("	h2 {\r\n");
      out.write("		font-size: 24px;\r\n");
      out.write("	}\r\n");
      out.write("	.product-name {\r\n");
      out.write("		font-size: 16px;\r\n");
      out.write("	}\r\n");
      out.write("	.product-price {\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("	}\r\n");
      out.write("	.btn-minus, .btn-plus {\r\n");
      out.write("		padding: 4px 8px;\r\n");
      out.write("	}\r\n");
      out.write("	.quantity {\r\n");
      out.write("		width: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	.btn-checkout {\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		font-size: 16px;\r\n");
      out.write("	}\r\n");
      out.write("	.cart-total {\r\n");
      out.write("		font-size: 16px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write(".icon-header-dropdown {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("    display: none; /* Ẩn menu mặc định */\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 100%;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul li {\r\n");
      out.write("    padding: 8px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu ul li a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-header-dropdown:hover .dropdown-menu {\r\n");
      out.write("    display: block; /* Hiển thị menu khi hover */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"animsition\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	<header class=\"header-v4\">\r\n");
      out.write("		<!-- Header desktop -->\r\n");
      out.write("		<div class=\"container-menu-desktop\">\r\n");
      out.write("			<!-- Topbar -->\r\n");
      out.write("			<div class=\"top-bar\">\r\n");
      out.write("				<div class=\"content-topbar flex-sb-m h-full container\">\r\n");
      out.write("					<div class=\"left-top-bar\">Trang nhóm bán hàng thời trang nhóm 17\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"wrap-menu-desktop how-shadow1\">\r\n");
      out.write("				<nav class=\"limiter-menu-desktop container\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Logo desktop -->\r\n");
      out.write("					<a href=\"#\" class=\"logo\"> <img src=\"assetsquantri/img/logo.png\"\r\n");
      out.write("						alt=\"IMG-LOGO\">\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<!-- Menu desktop -->\r\n");
      out.write("					<div class=\"menu-desktop\">\r\n");
      out.write("						<ul class=\"main-menu\">\r\n");
      out.write("							<li><a href=\"Laydulieusanpham\">Trang chủ</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"Cuahang\">Cửa hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"active-menu\" class=\"label1\" data-label1=\"hot\"><a\r\n");
      out.write("								href=\"Giohang\">Giỏ hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"blog.jsp\">Blog</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"about.jsp\">Giới thiệu</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"contact.jsp\">Liên hệ</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- Icon header -->\r\n");
      out.write("					<div class=\"wrap-icon-header flex-w flex-r-m\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search\">\r\n");
      out.write("							<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div\r\n");
      out.write("						");

						Laydulieuchonguoidung lgn = new Laydulieuchonguoidung();
							List<GioHang> gh = lgn.LayHetThongTinGioHang();
							HttpSession tk = request.getSession(false);
							List<User> user = (List<User>) tk.getAttribute("Ghinhotaikhoan");
							int soluong = 0;
							float tongTien = 0;
							if(user != null){
							for(GioHang gioHang:gh){
								for(User u : user)
									if(u.getMaTaiKhoan()==gioHang.getMaNguoiDung()){
								soluong += gioHang.getSoLuong();
								tongTien += gioHang.getGia();
									}
							}
							}
						
      out.write("\r\n");
      out.write("							class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart\"\r\n");
      out.write("							data-notify=\"");
      out.print(soluong);
      out.write("\">\r\n");
      out.write("							<i class=\"zmdi zmdi-shopping-cart\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"icon-header-dropdown\">\r\n");
      out.write("							<a href=\"#\"\r\n");
      out.write("								class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11\">\r\n");
      out.write("								<i class=\"fa fa-user\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							<!-- Thẻ con chứa thông tin cá nhân và đơn hàng -->\r\n");
      out.write("							<div class=\"dropdown-menu\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"Thongtincanhan.jsp\">Thông tin cá nhân</a></li>\r\n");
      out.write("									<li><a href=\"Thongtindonhangdamua.jsp\">Đơn hàng</a></li>\r\n");
      out.write("									<li><a href=\"Dangxuat\">Đăng xuất</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Header Mobile -->\r\n");
      out.write("		<div class=\"wrap-header-mobile\">\r\n");
      out.write("			<!-- Logo moblie -->\r\n");
      out.write("			<div class=\"logo-mobile\">\r\n");
      out.write("				<a href=\"Laydulieusanpham\"><img src=\"assetsquantri/img/logo.png\"\r\n");
      out.write("					alt=\"IMG-LOGO\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Icon header -->\r\n");
      out.write("			<div class=\"wrap-icon-header flex-w flex-r-m\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search\">\r\n");
      out.write("					<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				");

				if (user != null) {
					for (GioHang gioHang : gh) {
						for (User u : user)
					if (u.getMaTaiKhoan() == gioHang.getMaNguoiDung()) {
						soluong += gioHang.getSoLuong();
						tongTien += gioHang.getGia();
					}
					}

				}
				
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart\"\r\n");
      out.write("					data-notify=\"");
      out.print(soluong);
      out.write("\">\r\n");
      out.write("					<i class=\"zmdi zmdi-shopping-cart\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"icon-header-dropdown\">\r\n");
      out.write("					<a href=\"#\"\r\n");
      out.write("						class=\"icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11\"> <i\r\n");
      out.write("						class=\"fa fa-user\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<!-- Thẻ con chứa thông tin cá nhân và đơn hàng -->\r\n");
      out.write("					<div class=\"dropdown-menu\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"Thongtincanhan.jsp\">Thông tin cá nhân</a></li>\r\n");
      out.write("							<li><a href=\"Thongtindonhangdamua.jsp\">Đơn hàng</a></li>\r\n");
      out.write("							<li><a href=\"Dangxuat\">Đăng xuất</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Button show menu -->\r\n");
      out.write("			<div class=\"btn-show-menu-mobile hamburger hamburger--squeeze\">\r\n");
      out.write("				<span class=\"hamburger-box\"> <span class=\"hamburger-inner\"></span>\r\n");
      out.write("				</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Menu Mobile -->\r\n");
      out.write("		<div class=\"menu-mobile\">\r\n");
      out.write("			<ul class=\"topbar-mobile\">\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"left-top-bar\">Miễn phí giao hàng cho đơn từ $100\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"right-top-bar flex-w h-full\">\r\n");
      out.write("						<a href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> Trợ giúp & FAQs\r\n");
      out.write("						</a> <a href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> Tài khoản của\r\n");
      out.write("							tôi </a> <a href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> VN </a> <a\r\n");
      out.write("							href=\"#\" class=\"flex-c-m p-lr-10 trans-04\"> USD </a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"main-menu-m\">\r\n");
      out.write("				<li><a href=\"Laydulieusanpham\">Trang chủ</a> <span\r\n");
      out.write("					class=\"arrow-main-menu-m\"> <i class=\"fa fa-angle-right\"\r\n");
      out.write("						aria-hidden=\"true\"></i>\r\n");
      out.write("				</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"Cuahang\">Cửa hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"Giohang\" class=\"label1 rs1\" data-label1=\"hot\">Giỏ\r\n");
      out.write("						hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"blog.jsp\">Blog</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"about.jsp\">Giới thiệu</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"contact.jsp\">Liên hệ</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal Search -->\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"modal-search-header flex-c-m trans-04 js-hide-modal-search\">\r\n");
      out.write("			<div class=\"container-search-header\">\r\n");
      out.write("				<button\r\n");
      out.write("					class=\"flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search\">\r\n");
      out.write("					<img src=\"images/icons/icon-close2.png\" alt=\"CLOSE\">\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<form class=\"wrap-search-header flex-w p-l-15\">\r\n");
      out.write("					<button class=\"flex-c-m trans-04\">\r\n");
      out.write("						<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("					<input class=\"plh3\" type=\"text\" name=\"search\"\r\n");
      out.write("						placeholder=\"Search...\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<!-- Cart -->\r\n");
      out.write("	<div class=\"wrap-header-cart js-panel-cart\" >\r\n");
      out.write("		<div class=\"s-full js-hide-cart\"></div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"header-cart flex-col-l p-l-65 p-r-25\">\r\n");
      out.write("			<div class=\"header-cart-title flex-w flex-sb-m p-b-8\">\r\n");
      out.write("				<span class=\"mtext-103 cl2\"> Giỏ hàng </span>\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart\" >\r\n");
      out.write("					<i class=\"zmdi zmdi-close\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"header-cart-content flex-w js-pscroll\">\r\n");
      out.write("				<ul class=\"header-cart-wrapitem w-full\">\r\n");
      out.write("				");

				if(user != null){
				for(GioHang giohang : gh){
					for(User u : user){
					if(u.getMaTaiKhoan()==giohang.getMaNguoiDung()){	
					
				
      out.write("\r\n");
      out.write("					<li class=\"header-cart-item flex-w flex-t m-b-12\">\r\n");
      out.write("						<div class=\"header-cart-item-img\">\r\n");
      out.write("							<img src=\"");
      out.print(giohang.getDuongDan() );
      out.write("\" alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"header-cart-item-txt p-t-8\">\r\n");
      out.write("							<a href=\"#\" class=\"header-cart-item-name m-b-18 hov-cl1 trans-04\">\r\n");
      out.write("								White Shirt Pleat </a> <span class=\"header-cart-item-info\"> ");
      out.print(giohang.getSoLuong() );
      out.write("\r\n");
      out.write("								x $");
      out.print(giohang.getGia() );
      out.write(" </span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					");
}} }}
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"w-full\">\r\n");
      out.write("					<div class=\"header-cart-total w-full p-tb-40\">Tổng tiền: $");
      out.print(tongTien );
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"header-cart-buttons flex-w w-full\">\r\n");
      out.write("						<a href=\"Giohang\"\r\n");
      out.write("							class=\"flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10\">\r\n");
      out.write("							Xem giỏ hàng </a> <a href=\"Giohang\"\r\n");
      out.write("							class=\"flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10\">\r\n");
      out.write("							Kiểm tra </a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Shoping Cart -->\r\n");
      out.write("	<div class=\"cart-container\" style=\"marigin-top: 0px\">\r\n");
      out.write("		");

		String loi = (String) request.getAttribute("loi");
		if (loi != null) {
		
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("	alert(\"Xóa không thành công\");\r\n");
      out.write("	</script>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("		");

		List<GioHang> gioHang = (List<GioHang>) request.getAttribute("gioHang");
		float tongGia = 0;
		for (GioHang g : gioHang) {
			tongGia += g.getGia();
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"cart-item\" id=\"product1\" style=\"marigin-top: -70px\">\r\n");
      out.write("			<img src=\"");
      out.print(g.getDuongDan());
      out.write("\" alt=\"Sản phẩm 1\"\r\n");
      out.write("				class=\"product-image\">\r\n");
      out.write("			<div class=\"product-info\">\r\n");
      out.write("				<h3 class=\"product-name\">");
      out.print(g.getTenSanPham());
      out.write("</h3>\r\n");
      out.write("				<p class=\"product-price\" data-price=\"");
      out.print(g.getGia());
      out.write('"');
      out.write('>');
      out.print(g.getGia());
      out.write("</p>\r\n");
      out.write("				<p class=\"product-color\">\r\n");
      out.write("					Màu:\r\n");
      out.write("					");
      out.print(g.getMauSac());
      out.write("</p>\r\n");
      out.write("				<p class=\"product-color\">\r\n");
      out.write("					Kích cỡ:\r\n");
      out.write("					");
      out.print(g.getKichThuoc());
      out.write("</p>\r\n");
      out.write("				<div class=\"quantity-control\">\r\n");
      out.write("					<input type=\"number\" class=\"quantity\" id=\"quantity-product1\"\r\n");
      out.write("						value=\"");
      out.print(g.getSoLuong());
      out.write("\" min=\"1\" onchange=\"updateTotal()\">\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form action=\"Xoasanphamtrongdonhang\" method=\"post\">\r\n");
      out.write("				<input hidden=\"text\" value=\"");
      out.print(g.getMaGioHang());
      out.write("\" name=\"idGioHang\">\r\n");
      out.write("				<button class=\"btn-remove\" onclick=\"removeItem()\">Xóa</button>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"cart-total\">\r\n");
      out.write("			<p>\r\n");
      out.write("				Tổng cộng:\r\n");
      out.write("				");
      out.print(tongGia);
      out.write("</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<form action=\"ThanhToanGioHang\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("			<button class=\"btn-checkout\" type=\"submit\">Thanh toán</button>\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<footer class=\"bg3 p-t-75 p-b-32\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">Danh mục</h4>\r\n");
      out.write("\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Nữ </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Nam </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Giày </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Đồng hồ </a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">Trợ giúp</h4>\r\n");
      out.write("\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Theo dõi đơn </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Hoàn trả </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> Giao hàng </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"p-b-10\"><a href=\"#\"\r\n");
      out.write("							class=\"stext-107 cl7 hov-cl1 trans-04\"> FAQs </a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">LIÊN LẠC</h4>\r\n");
      out.write("\r\n");
      out.write("					<p class=\"stext-107 cl7 size-201\">Có bất kì câu hỏi nào? Hãy\r\n");
      out.write("						đến cửa hàng chúng tôi tại 8th floor, 379 Hudson St, New York, NY\r\n");
      out.write("						10018 hoặc gọi đến số (+84) 96 716 6879</p>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"p-t-27\">\r\n");
      out.write("						<a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\"> <i\r\n");
      out.write("							class=\"fa fa-facebook\"></i>\r\n");
      out.write("						</a> <a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\"> <i\r\n");
      out.write("							class=\"fa fa-instagram\"></i>\r\n");
      out.write("						</a> <a href=\"#\" class=\"fs-18 cl7 hov-cl1 trans-04 m-r-16\"> <i\r\n");
      out.write("							class=\"fa fa-pinterest-p\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-3 p-b-50\">\r\n");
      out.write("					<h4 class=\"stext-301 cl0 p-b-30\">Đăng ký nhận thông báo</h4>\r\n");
      out.write("\r\n");
      out.write("					<form>\r\n");
      out.write("						<div class=\"wrap-input1 w-full p-b-4\">\r\n");
      out.write("							<input class=\"input1 bg-none plh1 stext-107 cl7\" type=\"text\"\r\n");
      out.write("								name=\"email\" placeholder=\"email@example.com\">\r\n");
      out.write("							<div class=\"focus-input1 trans-04\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"p-t-18\">\r\n");
      out.write("							<button\r\n");
      out.write("								class=\"flex-c-m stext-101 cl0 size-103 bg1 bor1 hov-btn2 p-lr-15 trans-04\">\r\n");
      out.write("								Đăng kí</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"p-t-40\">\r\n");
      out.write("				<div class=\"flex-c-m flex-w p-b-18\">\r\n");
      out.write("					<a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-01.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-02.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-03.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-04.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a> <a href=\"#\" class=\"m-all-1\"> <img\r\n");
      out.write("						src=\"images/icons/icon-pay-05.png\" alt=\"ICON-PAY\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<p class=\"stext-107 cl6 txt-center\">\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					Copyright &copy;\r\n");
      out.write("					<script>document.write(new Date().getFullYear());</script>\r\n");
      out.write("					All rights reserved | Made with <i class=\"fa fa-heart-o\"\r\n");
      out.write("						aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\"\r\n");
      out.write("						target=\"_blank\">Colorlib</a> &amp; distributed by <a\r\n");
      out.write("						href=\"https://themewagon.com\" target=\"_blank\">ThemeWagon</a>\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Back to top -->\r\n");
      out.write("	<div class=\"btn-back-to-top\" id=\"myBtn\">\r\n");
      out.write("		<span class=\"symbol-btn-back-to-top\"> <i\r\n");
      out.write("			class=\"zmdi zmdi-chevron-up\"></i>\r\n");
      out.write("		</span>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/animsition/js/animsition.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/bootstrap/js/popper.js\"></script>\r\n");
      out.write("	<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/select2/select2.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\".js-select2\").each(function(){\r\n");
      out.write("			$(this).select2({\r\n");
      out.write("				minimumResultsForSearch: 20,\r\n");
      out.write("				dropdownParent: $(this).next('.dropDownSelect2')\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/MagnificPopup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"vendor/perfect-scrollbar/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.js-pscroll').each(function(){\r\n");
      out.write("			$(this).css('position','relative');\r\n");
      out.write("			$(this).css('overflow','hidden');\r\n");
      out.write("			var ps = new PerfectScrollbar(this, {\r\n");
      out.write("				wheelSpeed: 1,\r\n");
      out.write("				scrollingThreshold: 1000,\r\n");
      out.write("				wheelPropagation: false,\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(window).on('resize', function(){\r\n");
      out.write("				ps.update();\r\n");
      out.write("			})\r\n");
      out.write("		});\r\n");
      out.write("		 // Hàm cập nhật số lượng\r\n");
      out.write("		 function updateQuantity(productId, change) {\r\n");
      out.write("            const quantityInput = document.querySelector(`#quantity-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("            let quantity = parseInt(quantityInput.value);\r\n");
      out.write("            quantity += change;\r\n");
      out.write("            if (quantity < 1) quantity = 1; // Số lượng không thể nhỏ hơn 1\r\n");
      out.write("            quantityInput.value = quantity;\r\n");
      out.write("            updateTotal();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Hàm tính tổng giá\r\n");
      out.write("        function updateTotal() {\r\n");
      out.write("            let total = 0;\r\n");
      out.write("            const productItems = document.querySelectorAll('.cart-item');\r\n");
      out.write("            productItems.forEach(item => {\r\n");
      out.write("                const priceElement = item.querySelector('.product-price');\r\n");
      out.write("                const price = parseFloat(priceElement.getAttribute('data-price'));\r\n");
      out.write("                const quantity = parseInt(item.querySelector('.quantity').value);\r\n");
      out.write("                total += price * quantity;\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            document.querySelector('#total-price').textContent = `Tổng cộng: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total.toLocaleString()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" VND`;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Hàm xóa sản phẩm khỏi giỏ\r\n");
      out.write("        function removeItem() {\r\n");
      out.write("        	if (confirm(\"Bạn có chắc chắn muốn xóa sản phẩm này khỏi giỏ hàng?\")) {\r\n");
      out.write("        	    // Nếu người dùng nhấn \"OK\"\r\n");
      out.write("        	    console.log(\"Đã xóa sản phẩm!\");\r\n");
      out.write("        	} else {\r\n");
      out.write("        	    // Nếu người dùng nhấn \"Cancel\"\r\n");
      out.write("        	    console.log(\"Hủy thao tác xóa.\");\r\n");
      out.write("        	}\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Khởi tạo tổng giá trị khi tải trang\r\n");
      out.write("        updateTotal();\r\n");
      out.write("	</script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
